### ISSUE TITLE
strange problem with las file

### ISSUE THREAD

**Issue by diverdude** [kinverarity1/lasio#104]
Hi, i am trying to read a lasfile v.2, but get an error saying: 

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/home/kalo/anaconda3/lib/python3.4/site-packages/lasio/las.py in read_section(self, section_name)
    517             try:
--> 518                 values = read_line(line)
    519             except:

/home/kalo/anaconda3/lib/python3.4/site-packages/lasio/las.py in read_line(line, pattern)
    662     m = re.match(pattern, line)
--> 663     mdict = m.groupdict()
    664     if mdict["name"] == "":

AttributeError: 'NoneType' object has no attribute 'groupdict'

During handling of the above exception, another exception occurred:

LASHeaderError                            Traceback (most recent call last)
<ipython-input-2-7cb6406c58c4> in <module>()
----> 1 lf = lasio.LASFile('/media/kalo/448C-AF0D/260815/DASDTS_2015-08-26T11-30-34.dts')

/home/kalo/anaconda3/lib/python3.4/site-packages/lasio/las.py in __init__(self, file_ref, **kwargs)
    164 
    165         if not (file_ref is None):
--> 166             self.read(file_ref, **kwargs)
    167 
    168     def read(self, file_ref, **kwargs):

/home/kalo/anaconda3/lib/python3.4/site-packages/lasio/las.py in read(self, file_ref, **kwargs)
    209         reader.wrap = self.version['WRAP'].value == 'YES'
    210 
--> 211         self.well = reader.read_section('~W')
    212         self.curves = reader.read_list_section('~C')
    213         try:

/home/kalo/anaconda3/lib/python3.4/site-packages/lasio/las.py in read_section(self, section_name)
    520                 raise LASHeaderError("Failed in %s section on line:\n%s%s" % (
    521                     section_name, line,
--> 522                     traceback.format_exc().splitlines()[-1]))
    523             else:
    524                 d[values['name']] = parser(**values)

LASHeaderError: Failed in ~W section on line:
TIMESTAMP: 2015/08/26 11:30:34AttributeError: 'NoneType' object has no attribute 'groupdict'

IS this some problem with the lasio library?

//////////////////// The LAS file ////////////////////

~Version Information
VERS.                      2.0: CWLS Log ASCII Standard - VERSION 2.0
WRAP.                      NO: One line per depth step
~Well Information Block
STRT.m                 0.0000:
STOP.m              5299.4238:
STEP.m                 0.6806:
NULL.             -999.2500:
TIMESTAMP: 2015/08/26 11:30:34
COMP.                         : COMPANY
WELL.                         : WELL
FLD.                          : FIELD
LOC.                          : LOCATION
PROV.                         : PROVINCE
CNTY.                         : COUNTRY
SRVC.                         : SERVICE COMPANY
DATE.                         : LOG DATE
UWI.                          : UNIQUE WELL ID
~Curve Information Block
DEPTH.m
DAS_EN00.Unity
DAS_EN01.Unity
DAS_EN02.Unity
DAS_EN03.Unity
DAS_EN04.Unity
DAS_EN05.Unity
~A DEPTH TEMP_DTS DAS_ENERGY
    0.0000              8459           114.2          107.06           895.1          2475.7          4866.9
    0.6806             13717          3881.4          491.92          1708.6          2744.8          4890.7
    1.3613             29862           17167          1648.2          2970.4          3175.2          4901.4
    2.0419             61740           42725          3469.4          5674.1          4779.2          5092.6
    2.7225       1.1135e+005           83468          6621.3          9205.7          6689.6          5368.8
    3.4032       1.2074e+005           93058          6812.6            9212          6664.7            4990

**Comment by kinverarity1** [comment]
The TIMESTAMP mnemonic does not have a period following it, so it is a non compliant file.


However the regular expression can probably be tweaked to cope with this example. I will have a play with it.


Thanks!




On Thu, Aug 27, 2015 at 6:50 AM -0700, "diverdude" <notifications@github.com> wrote:
Hi, i am trying to read a lasfile v.2, but get an error saying:

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/home/kalo/anaconda3/lib/python3.4/site-packages/lasio/las.py in read_section(self, section_name)
    517             try:
--> 518                 values = read_line(line)
    519             except:

/home/kalo/anaconda3/lib/python3.4/site-packages/lasio/las.py in read_line(line, pattern)
    662     m = re.match(pattern, line)
--> 663     mdict = m.groupdict()
    664     if mdict["name"] == "":

AttributeError: 'NoneType' object has no attribute 'groupdict'

During handling of the above exception, another exception occurred:

LASHeaderError                            Traceback (most recent call last)
<ipython-input-2-7cb6406c58c4> in <module>()
----> 1 lf = lasio.LASFile('/media/kalo/448C-AF0D/260815/DASDTS_2015-08-26T11-30-34.dts')

/home/kalo/anaconda3/lib/python3.4/site-packages/lasio/las.py in __init__(self, file_ref, **kwargs)
    164
    165         if not (file_ref is None):
--> 166             self.read(file_ref, **kwargs)
    167
    168     def read(self, file_ref, **kwargs):

/home/kalo/anaconda3/lib/python3.4/site-packages/lasio/las.py in read(self, file_ref, **kwargs)
    209         reader.wrap = self.version['WRAP'].value == 'YES'
    210
--> 211         self.well = reader.read_section('~W')
    212         self.curves = reader.read_list_section('~C')
    213         try:

/home/kalo/anaconda3/lib/python3.4/site-packages/lasio/las.py in read_section(self, section_name)
    520                 raise LASHeaderError("Failed in %s section on line:\n%s%s" % (
    521                     section_name, line,
--> 522                     traceback.format_exc().splitlines()[-1]))
    523             else:
    524                 d[values['name']] = parser(**values)

LASHeaderError: Failed in ~W section on line:
TIMESTAMP: 2015/08/26 11:30:34AttributeError: 'NoneType' object has no attribute 'groupdict'


IS this some problem with the lasio library?

//////////////////// The LAS file ////////////////////

~Version Information
VERS.                      2.0: CWLS Log ASCII Standard - VERSION 2.0
WRAP.                      NO: One line per depth step
~Well Information Block
STRT.m                 0.0000:
STOP.m              5299.4238:
STEP.m                 0.6806:
NULL.             -999.2500:
TIMESTAMP: 2015/08/26 11:30:34
COMP.                         : COMPANY
WELL.                         : WELL
FLD.                          : FIELD
LOC.                          : LOCATION
PROV.                         : PROVINCE
CNTY.                         : COUNTRY
SRVC.                         : SERVICE COMPANY
DATE.                         : LOG DATE
UWI.                          : UNIQUE WELL ID
~Curve Information Block
DEPTH.m
DAS_EN00.Unity
DAS_EN01.Unity
DAS_EN02.Unity
DAS_EN03.Unity
DAS_EN04.Unity
DAS_EN05.Unity
~A DEPTH TEMP_DTS DAS_ENERGY
    0.0000              8459           114.2          107.06           895.1          2475.7          4866.9
    0.6806             13717          3881.4          491.92          1708.6          2744.8          4890.7
    1.3613             29862           17167          1648.2          2970.4          3175.2          4901.4
    2.0419             61740           42725          3469.4          5674.1          4779.2          5092.6
    2.7225       1.1135e+005           83468          6621.3          9205.7          6689.6          5368.8
    3.4032       1.2074e+005           93058          6812.6            9212          6664.7            4990

---
Reply to this email directly or view it on GitHub:
https://github.com/kinverarity1/lasio/issues/104

**Comment by kinverarity1** [comment]
Also this is quite a mess in any case as the actual datetime following the TIMESTAMP comes after the colon, but in a LAS v2 I think it is meant to come before. The fact that the value also contains colons adds to the difficulty in passing such a malformed line.


The regular expression could not be tweaked to properly read that TIMESTAMP line, although it may be tweaked to at least not raise an exception in a lazy reading mode.




On Thu, Aug 27, 2015 at 6:50 AM -0700, "diverdude" <notifications@github.com> wrote:
Hi, i am trying to read a lasfile v.2, but get an error saying:

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/home/kalo/anaconda3/lib/python3.4/site-packages/lasio/las.py in read_section(self, section_name)
    517             try:
--> 518                 values = read_line(line)
    519             except:

/home/kalo/anaconda3/lib/python3.4/site-packages/lasio/las.py in read_line(line, pattern)
    662     m = re.match(pattern, line)
--> 663     mdict = m.groupdict()
    664     if mdict["name"] == "":

AttributeError: 'NoneType' object has no attribute 'groupdict'

During handling of the above exception, another exception occurred:

LASHeaderError                            Traceback (most recent call last)
<ipython-input-2-7cb6406c58c4> in <module>()
----> 1 lf = lasio.LASFile('/media/kalo/448C-AF0D/260815/DASDTS_2015-08-26T11-30-34.dts')

/home/kalo/anaconda3/lib/python3.4/site-packages/lasio/las.py in __init__(self, file_ref, **kwargs)
    164
    165         if not (file_ref is None):
--> 166             self.read(file_ref, **kwargs)
    167
    168     def read(self, file_ref, **kwargs):

/home/kalo/anaconda3/lib/python3.4/site-packages/lasio/las.py in read(self, file_ref, **kwargs)
    209         reader.wrap = self.version['WRAP'].value == 'YES'
    210
--> 211         self.well = reader.read_section('~W')
    212         self.curves = reader.read_list_section('~C')
    213         try:

/home/kalo/anaconda3/lib/python3.4/site-packages/lasio/las.py in read_section(self, section_name)
    520                 raise LASHeaderError("Failed in %s section on line:\n%s%s" % (
    521                     section_name, line,
--> 522                     traceback.format_exc().splitlines()[-1]))
    523             else:
    524                 d[values['name']] = parser(**values)

LASHeaderError: Failed in ~W section on line:
TIMESTAMP: 2015/08/26 11:30:34AttributeError: 'NoneType' object has no attribute 'groupdict'


IS this some problem with the lasio library?

//////////////////// The LAS file ////////////////////

~Version Information
VERS.                      2.0: CWLS Log ASCII Standard - VERSION 2.0
WRAP.                      NO: One line per depth step
~Well Information Block
STRT.m                 0.0000:
STOP.m              5299.4238:
STEP.m                 0.6806:
NULL.             -999.2500:
TIMESTAMP: 2015/08/26 11:30:34
COMP.                         : COMPANY
WELL.                         : WELL
FLD.                          : FIELD
LOC.                          : LOCATION
PROV.                         : PROVINCE
CNTY.                         : COUNTRY
SRVC.                         : SERVICE COMPANY
DATE.                         : LOG DATE
UWI.                          : UNIQUE WELL ID
~Curve Information Block
DEPTH.m
DAS_EN00.Unity
DAS_EN01.Unity
DAS_EN02.Unity
DAS_EN03.Unity
DAS_EN04.Unity
DAS_EN05.Unity
~A DEPTH TEMP_DTS DAS_ENERGY
    0.0000              8459           114.2          107.06           895.1          2475.7          4866.9
    0.6806             13717          3881.4          491.92          1708.6          2744.8          4890.7
    1.3613             29862           17167          1648.2          2970.4          3175.2          4901.4
    2.0419             61740           42725          3469.4          5674.1          4779.2          5092.6
    2.7225       1.1135e+005           83468          6621.3          9205.7          6689.6          5368.8
    3.4032       1.2074e+005           93058          6812.6            9212          6664.7            4990

---
Reply to this email directly or view it on GitHub:
https://github.com/kinverarity1/lasio/issues/104
