### ISSUE TITLE
Suggested backwards-incompatible change - LASFile.curves to go from list to ordered dictionary

### ISSUE THREAD

**Issue by kinverarity1** [kinverarity1/lasio#105]
I am thinking about making a backwards-incompatible change where the ``LASFile.curves`` attribute (currently a list of ``Curve`` objects) becomes an ``OrderedDictionary`` object, where the key is the curve mnemonic and the value is the ``Curve`` object.

This would make accessing all of the LAS file header section attributes identical -- ``version``, ``well``, and ``params`` are already ``OrderedDictionary`` objects. It would also allow me some other fixes and enhancements that would be a lot easier and make more sense if I make this change. Also much better internal structure looking towards LAS 3.0 support

Any comments? 

I bring it up because it would break existing code. 

I could support both by having ``curves_list`` and ``curves_dict`` attributes, and then ``curves`` could be either one -- I would leave it as a list for now and then in the future swap it over to dict. That would get me all of the benefits of the internal changes and less confusion for users.

**Comment by VelizarVESSELINOV** [comment]
Make sense for me, and should be easy to fix existing code (at least for me).

The only potential issue I can see for now is there are a lot of LAS files with the same curve name more than once, and for this you will need to manage adding same kind of suffix ``curve``_# but this will be not optimal for LAS read/write as you will change the output adding _# suffix, which is minor problem for me.

**Comment by kinverarity1** [comment]
OK good point. To make sure I understand you, take a file like this:

```
~C
DEPTH.m             : depth
RHO.ohmm            : resistivity 1
RHO.ohmm            : resistivity 2
RHO.ohmm            : resistivity 3
PHI.                : porosity
```

My suggested change would mean that it would read in like so:

```python
>>> l.curves
{"DEPTH": Curve(...),
 "RHO[1]": Curve(...),
 "RHO[2]": Curve(...),
 "RHO[3]": Curve(...),
 "PHI": Curve(...)
 }
```

And you are saying that on doing ``l.write(...)``, you would get, at the moment:

```
~C
DEPTH.m             : depth
RHO[1].ohmm         : resistivity 1
RHO[2].ohmm         : resistivity 2
RHO[3].ohmm         : resistivity 3
PHI.                : porosity
```

but that you would want it to reproduce the original curve mnemonics:

```
~C
DEPTH.m             : depth
RHO.ohmm            : resistivity 1
RHO.ohmm            : resistivity 2
RHO.ohmm            : resistivity 3
PHI.                : porosity
```

Am I right?

I think that's fine -- I can make that change. It's a separate issue, to make sure that any ``[n]`` mnemonic (or ``UNKNOWN``) changes that ``lasio`` makes get removed on writing the data out again.

**Comment by VelizarVESSELINOV** [comment]
Yes, you are right.

One potential extreme case to think about, how you distinguish curve with [..] suffix already with curve with duplicated name?
Example of LAS source file:
```
~C
DEPTH.m: depth
GR.gAPI: mean gamma ray value
GR.gAPI: corrected gamma ray value
GR[0].gAPI: gamma ray image at angle 0 dega
GR[1].gAPI: gamma ray image at angle 20 dega
...
GR[17].gAPI: gamma ray image at angle 340 dega
```
What will be the expected result of ``l.write(...)``?

**Comment by kinverarity1** [comment]
The expected result - once I make these changes! - of ``l.write`` is to reproduce the original mnemonics. So you should get

```
DEPTH.m     : depth
GR.gAPI     : mean gamma ray value
GR.gAPI     : corrected gamma ray value
GR[0].gAPI  : gamma ray image at angle 0 dega
GR[1].gAPI  : gamma ray image at angle 20 dega
...
GR[17].gAPI : gamma ray image at angle 340 dega
```

in the output LAS.

On the other hand what the keys of the ``curves`` dictionary would be, I'm not sure. The algorithm I was thinking would have silently overwritten data for this example.

Any ideas? All I can come up with for now is:

A) ``GR[18]``, ``GR[19]`` - I don't like this idea given that they will come in the list before ``GR[0]``, ``GR[1]`` etc.
B) ``GR_[0]``, ``GR_[1]`` - not keen on this either, very arbitrary
C) ``GR[][0]``, ``GR[][1]`` - looks odd but I like it more than the others

**Comment by VelizarVESSELINOV** [comment]
I would suggest you to use character that is almost forbidden in LAS mnemonic like ":" or ".". This force you to remove the suffix when you write output LAS and make you almost impossible to have duplication of key. So the dictionary key can be something like ``GR.1`` or ``GR:1``.

How do you plan to store the order of the mnemonic channels of the original file and specially the first one that have special meaning as reference with the associated properties like STRT, STOP, STEP?

**Comment by kinverarity1** [comment]
Excellent suggestion, thank you! I will use a period like``GR.1``, ``GR.2``.

The order of the mnemonics is already taken care of for the ~Version, ~Well,  and ~Parameters sections - each header item with its mnemonic is stored in the order they are read in (that is why I use a ``collections.ordereddict`` subclass rather than an ordinary dictionary) and with these changes I'll also add a feature for comment lines to be treated the same way - a step along the way to having output files written to be very similar to input files. This issue is essentially about extending this approach to the ~Curves section, which started out being treated differently for reasons which are no longer relevant. 

Regarding STRT, STOP etc, I presume you are referring to LASFile objects being created from scratch? There is essentially a default order and structure created for such objects already.

**Comment by kinverarity1** [comment]
Or do you mean the reference curve i.e. ``DEPTH``?

**Comment by VelizarVESSELINOV** [comment]
Yes, reference curve mnemonic in case you have dict of mnemonics like this {"TVD", "TVDSS", "MD", "CDEPTH", "TVT"}, how you know which mnemonic channel is the famous reference curve?

**Comment by kinverarity1** [comment]
The reference curve is always going to be the first mnemonic. 

Obviously if it were an ordinary dictionary that would not work, but it will be an ordered dictionary, so whether you use ``l.curves.keys()`` for the mnemonics, ``l.curves.values()`` for the Curve objects, or ``l.curves.items()`` for both, you'll get the reference curve first.

**Comment by VelizarVESSELINOV** [comment]
Cool, great :)

**Comment by kinverarity1** [comment]
This is close to finished in the 'curves' branch - just need to review the issues and PR comments and make sure all the notebooks run and make sense, then merge.

Now that this is done I should be able to work on LAS 3 support.
