### ISSUE TITLE
LASFile object should be serializable with json.dumps()

### ISSUE THREAD

**Issue by knbknb** [kinverarity1/lasio#107]
I'd like to dump the lasfile into Redis (a popular nosql database), or save it to disk in the platform-independent JSON Format. 
At this time, this is not possible. 

<pre>
import redis
import json
r = redis.StrictRedis(host='localhost', port=6379, db=0)
#json_images = json.dumps(lasobj) # DOES NOT WORK
json_images = json.dumps(lasobj, default=lambda x: None)
r.set('lasobj', json_images)
    TypeError: array([ 134.5946,  134.62  ,  134.6454, ...,  745.6424,  745.6678,
        745.6932]) is not JSON serializable
</pre>

**Comment by kinverarity1** [comment]
I'll fix this - it should work directly with ``json.dumps()``.

**Comment by kinverarity1** [comment]
#111 provides a partial fix:

```python
json_images = json.dumps(lasobj, cls=lasio.JSONEncoder)
```

will work (a unit test for it has been added).

However the JSON representation only contains the data, not the header information.

I think a better solution would be to provide a ``LASFile.json`` attribute which covers all the information in the file. I'll leave this issue open for now.

**Comment by kinverarity1** [comment]
I should align this with whatever format JustinGOSSES/wellio.js settles on.

**Comment by kinverarity1** [comment]
This looks sensible: https://github.com/JSONWellLogFormat/JSONWellLogFormat

We should provide a `LASFile.to_json()` method which uses the serializer above.

And, why not, a `from_json()` class method.

**Comment by dcslagel** [comment]
https://github.com/JustinGOSSES/wellio.js/pull/36 is an exploration and discussion PR about the json format for JustinGOSSES/wellio.js.  

It includes:
-  wellio_sample_2.0.json : a full wellio json file based on sample_v2.0.las
- wellio.schema.json : an initial sketch of what a Wellio son-schema might look like.  In the first commit, only the Version section is specified.

Is this useful with regards to Lasio's json roadmap?

DC

**Comment by kinverarity1** [comment]
Absolutely - looks great! 

I don't know anything about JSON schemas, so haven't got much to directly contribute to the discussion, but I certainly would prefer lasio's to_json() to go straight into any wellio "from_json()" and vice versa, so I am happy to follow wellio's lead here.

**Comment by dcslagel** [comment]
Just some background info..  A json-schema could both act as the specification to build to_json() and from_json() functions/classes on.  It would also enable testing and validation of the json files.

Here is a python example. It uses the jsonschema package at:
https://github.com/Julian/jsonschema
https://python-jsonschema.readthedocs.io/en/stable/

```bash
pip install jsonschema
cd wellio.js/assets/json_files

# No output seems to mean the json validated
# using  an exploratory wellio json-schema.
jsonschema  -i wellio_sample_2.0.json wellio.schema.json 

# Here is an example with the current lasio_sample_2.0.json 
# It reports Wellio's 'VERSION INFORMATION' property is missing but required. 
jsonschema  -i lasio_sample_2.0.json wellio.schema.json 
{'metadata': {... rest of json output ...}}: 
'VERSION INFORMATION' is a required property
``` 

So that is a way that a json-schema might be used. 

DC

**Comment by kinverarity1** [comment]
Ok, thanks!

**Comment by kinverarity1** [comment]
I'm closing this because I think we are meeting the original issue. Thanks everyone 👍

**Comment by scuervo91** [comment]
Hi. I've been looking for the feature to create a LASFile Object from a Json?

Are there any plans to implement that?

Thank you
