### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by bsdis** [kinverarity1/lasio#117]
Hi, i notice it says build failed on the version in pypi (https://pypi.python.org/pypi/lasio/) as well on github frontpage.
Is it far from build rdy?
What needs to be done before it builds?

**Comment by kinverarity1** [comment]
Sorry, this is minor, a wrongly-formatted print function is failing on the python 3+ tests. Fixing now.

**Comment by kinverarity1** [comment]
All passing now - thanks for reminding me of this bug.

**Comment by bsdis** [comment]
Thanks a lot for acting so quick.

**Comment by bsdis** [comment]
fyi in the overview it does not say lasio supports p3.5 but i think it does...at least i am able to import lasio 0.9.1 in python 3.5.
It is supported in 3.5 right?

**Comment by kinverarity1** [comment]
I'm not sure as I don't run 3.5 but I just added it to the [continuous integration tester](https://travis-ci.org/kinverarity1/lasio) and everything passes. So it looks like it is Python 3.5 compatible!
