### ISSUE TITLE
Add more static code analysis tools

### ISSUE THREAD

**Issue by VelizarVESSELINOV** [kinverarity1/lasio#119]
Please find suggestion for two additional badges:
 1. Python specific very good code quality analysis: https://www.quantifiedcode.com
 1. Multi-language quality analysis: https://www.codacy.com

**Comment by kinverarity1** [comment]
Thanks, those look pretty useful. Automatic PRs to fix code quality, yes please!

I'll add them sometime.

**Comment by VelizarVESSELINOV** [comment]
Thanks, looks good to see the results of the static code analysis.
