### ISSUE TITLE
Markdown tutorial for converting LAS > Excel using shell script

### ISSUE THREAD

**Issue by kinverarity1** [kinverarity1/lasio#121]
To do - refer to library explanation using

http://nbviewer.jupyter.org/github/kinverarity1/lasio/blob/master/notebooks/converting%20a%20LAS%20file%20to%20an%20Excel%20spreadsheet.ipynb

but the script is 

https://github.com/kinverarity1/lasio/blob/master/lasio/excel.py#L76

**Comment by Dutchmeister** [comment]
Hi,

I am quite new to this, but if I run the script as in the tuturial I get the following error:

AttributeError: 'module' object has no attribute 'ExcelConverter'

any suggestions?

**Comment by dagrha** [comment]
@Dutchmeister, one approach would be to use the pandas dataframe attribute of your lasio object, accessible with the `.df()` method. Then you can output it to an excel file with the `to_excel()` dataframe method. For example:
```
import lasio

las = lasio.LASfile('myLAS.las')
df = las.df()
df.to_excel('myLAS.xlsx')
```
This will only output the curve data and mnemonics (no LAS header info).

**Comment by kinverarity1** [comment]
@dagrha's approach should work ok.

However ExcelConverter should work - what happens if you use this code?

```python
import lasio
l = lasio.read('path/to/your/example.las')
e = lasio.ExcelConverter(l)
e.write('output.xlsx')
```

**Comment by kinverarity1** [comment]
@Dutchmeister Also the command-line script should work:

```bash
$ las2excel LAS_FILENAME XLSX_FILENAME
```

Let me know what command gives you the above error you mention "AttributeError: 'module' object has no attribute 'ExcelConverter'".

Also, what version of lasio do you have, and how did you install it?

**Comment by kinverarity1** [comment]
There are new scripts and examples in the documentation more completely explaining the LAS > Excel conversion.

https://lasio.readthedocs.io/en/latest/exporting.html#script-interfaces
