### ISSUE TITLE
Use mybinder.org as a playground

### ISSUE THREAD

**Issue by oliveirarodolfo** [kinverarity1/lasio#125]
As I started playing around with `lasio` I realised that it would be nice to provide a playground in [mybinder.org](http://mybinder.org) for it. It would serve as a tutorial with a single-click to start. I started creating a `lasio-notebooks` repository I can submit a pull request with the `environment.yml` for the conda package. That's pretty much what you need to start with mybinder.org (and the notebooks of course).

**Comment by kinverarity1** [comment]
Hey that's fantastic!

Is it ok if I use the badge from your [lasio-notebooks](https://github.com/oliveirarodolfo/lasio-notebooks) repo on the lasio README?

**Comment by oliveirarodolfo** [comment]
Sure take it all! That's practically yours, the first example is pretty much the `README.md` of your notebooks anyway! This could work as some sort of tutorial for newcomers.

It was part of my *learn-lasio-thing* and I was planning to review the `ipynb` files on your examples folder and then sharing it back to you, either the whole repository or as PR's to your notebooks.

As you have planned a refactoring of the `LASFile` class in #124, I thought that maybe it would be worth to keep the `/notebooks` (so as the `/issues`) folders out of the main `lasio` repository. For simplicity only. But honestly I'm not sure if this would affect your existing build routines.

**Comment by kinverarity1** [comment]
Thanks - I think for a variety of reasons the example notebooks would belong better in a separate lasio-notebooks repository such as the one you've built - it's a bit simpler perhaps for the link to binder.

The binder app is something special, I'm amazed it's so accessible.

The issues notebooks ones I find helpful for development so might as well just leave those here.

**Comment by oliveirarodolfo** [comment]
Yeah! The one-click jupyter deployment right from a badge couldn't get any simpler! 

Indeed the `lasio-notebooks` repository is simple! I've just started it, had no time to actually do any decent work on it. You are right on the issues notebooks, I tend to use a bunch of notebooks like that as well.

**Comment by kinverarity1** [comment]
I'm going to close this as the [lasio-notebooks repository](https://github.com/oliveirarodolfo/lasio-notebooks) is now linked from the lasio README, and I will contribute to the series of tutorials you've started there via PRs. Thanks!

**Comment by oliveirarodolfo** [comment]
Ow that's perfect! I just added you as a Collaborator.

**Comment by kinverarity1** [comment]
Thanks!
