### ISSUE TITLE
lasio.exceptions.LASDataError: Failed to read wrapped data: ValueError: could not convert string to float: ~Version

### ISSUE THREAD

**Issue by mohanvn** [kinverarity1/lasio#131]
Hello,

I would like to Thank You people very much for very good the LAS parser which saved lot of effort in writing an LAS parser and for making it easy to use. Recently, I ran into an error while parsing an LAS file. Can you please look into the above mentioned error for the file attached here.
[sample.zip](https://github.com/kinverarity1/lasio/files/192085/sample.zip)

File "build\bdist.win32\egg\lasio\__init__.py", line 38, in read
  File "build\bdist.win32\egg\lasio\las.py", line 81, in __init__
  File "build\bdist.win32\egg\lasio\las.py", line 139, in read
  File "build\bdist.win32\egg\lasio\reader.py", line 167, in read_data
lasio.exceptions.LASDataError: Failed to read wrapped data: ValueError: could not convert string to float: ~Version

**Comment by mohanvn** [comment]
Seems to be failing because every second line in the ASCII Data section fewer than 7 curves, just like mentioned in the below

Depth
    DPHI        SP  
 7999.0000 
    0.2990  -999.2500 
 8000.0000 
    0.0860   -42.3610

Please help me know if someone happens to written a small code for handling this. Thank You in advance!!

**Comment by kinverarity1** [comment]
Hi!  Thanks for the report, I'll have a look at this today. Sorry about the delay!

**Comment by mohanvn** [comment]
Thanks for the reply, the issue seems to be having two pairs of data i.e., there is another ~Version Information at line 13916. There is any way we can handle this and have both of them parsed in the same program

**Comment by kinverarity1** [comment]
Oh I see - no, you need to split the files first, e.g.

```python
fn = 'sample.las'
chunks = [c for c in open(fn, 'r').read().split('~V') if c]
for i, chunk in enumerate(chunks):
    with open(fn.replace('.las', '_%d.las' % i), 'w') as f:
        f.write('~V' + chunk)
```

lasio won't support this in the package.
