### ISSUE TITLE
pickle deserialization does not work

### ISSUE THREAD

**Issue by danlapko** [kinverarity1/lasio#132]
Hi, I needs your help! I want serialize my project context, but lasio gives an error message during deseariliztion las file. Is it any ways to get around this problem?

```
 las = lasio.read('./805.las')
 f = open('las_file', 'wb')
 pickle.dump(las, f)
 #...
 f = open('las_file', 'rb')
 las = pickle.load(f)
```
An error occurred in line `las = pickle.load(f)`

Traceback:
```
File "../python3.4/site-packages/lasio/las.py", line 152, in __init__
    super(CurveItem, self).__init__(*args, **kwargs)
TypeError: __init__() missing 1 required positional argument: 'mnemonic'
```

**Comment by dagrha** [comment]
I am wondering if this [Stackoverflow](http://stackoverflow.com/questions/22690729/pickling-an-ordereddict-derived-object) question/answer is somehow relevant, since CurveItem inherits from the collections.OrderedDict class.

**Comment by kinverarity1** [comment]
Thanks for the report @danlapko. I'm getting a different error message but for me clearly pickling (or at least loading the pickled version) is [badly broken](https://github.com/kinverarity1/lasio/blob/pickle/notebooks/issues/132%20ordereddict%20pickle.ipynb).

Thanks @dagrha - I'm pretty sure there's something subtly wrong with how I've subclassed OrderedDict.

Working on it...

**Comment by danlapko** [comment]
I've set the default value of the mnemonic argument in CurveItem constructor as  empty line and now serialization works fine.

**Comment by kinverarity1** [comment]
Ah - what version of Python are you using?

________________________________

**Comment by danlapko** [comment]
3.4

**Comment by kinverarity1** [comment]
OK - looks like I still have a serialization error for < 3.4. Thanks for raising this!

**Comment by danlapko** [comment]
Oh, sorry I've made it in HeaderItem class
```
class HeaderItem(OrderedDict):
    def __init__(self, mnemonic="", unit="", value="", descr=""):
```

**Comment by kinverarity1** [comment]
Fixed now for pickling on all python versions.
