### ISSUE TITLE
Any support for .laz files?

### ISSUE THREAD

**Issue by sirgogo** [kinverarity1/lasio#136]
I would be willing to help out, if someone can point me in the right direction?

**Comment by kinverarity1** [comment]
What is a laz file?

If you are referring to compressed LiDAR data there is the library libLAS - https://pypi.python.org/pypi/libLAS

This library is for borehole data files, which coincidentally share the las file extension with LiDAR data files.



On Tue, Jul 12, 2016 at 7:08 AM +0930, "Abhejit Rajagopal" <notifications@github.com<mailto:notifications@github.com>> wrote:


I would be willing to help out, if someone can point me in the right direction?

-

**Comment by sirgogo** [comment]
[LAZ is a compressed format for LAS](http://www.laszip.org/). There is a utility in LAStools to uncompress to .las, but directly reading .laz directly in python would be convenient.

**Comment by kinverarity1** [comment]
From the linked page: "the de-facto standard for LiDAR compression.". You need to contact the authors of libLAS - https://pypi.python.org/pypi/libLAS. This library (lasio) is for a totally different kind of data.

________________________________
