### ISSUE TITLE
meta data not being written

### ISSUE THREAD

**Issue by bsdis** [kinverarity1/lasio#139]
Hi, I am creating a las file with lasio like this:
l = lasio.LASFile()
l.header.DATE = str(datetime.datetime.today())
l.header.COMP = 'mycompanyname'
l.add_curve('DEPT', depth, unit='m')
l.add_curve('FREQ', F['data'][1000,:,0], unit='hz')
with open(outfile, mode="w") as f: # Write LAS file to disk
    l.write(f)

But in the resulting files, the columns for COMP and DATE are both empty.
Like this:

COMP.                  : COMPANY
WELL.                  : WELL
FLD .                  : FIELD
LOC .                  : LOCATION
PROV.                  : PROVINCE
CNTY.                  : COUNTY
STAT.                  : STATE
CTRY.                  : COUNTRY
SRVC.                  : SERVICE COMPANY
DATE.                  : DATE
UWI .                  : UNIQUE WELL ID
API .                  : API NUMBER

Why is the inserted date and company name not listed?

**Comment by kinverarity1** [comment]
Try assigning values to the "value" attribute:

l.header.DATE.value =  str(datetime.datetime.today())

DATE is a LASHeaderItem with several attributes you can assign to: mnemonic, unit, value, and descr.



On Sun, Aug 14, 2016 at 10:35 PM +0930, "bsdis" <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi, I am creating a las file with lasio like this:
l = lasio.LASFile()
l.header.DATE = str(datetime.datetime.today())
l.header.COMP = 'mycompanyname'
l.add_curve('DEPT', depth, unit='m')
l.add_curve('FREQ', F['data'][1000,:,0], unit='hz')
with open(outfile, mode="w") as f: # Write LAS file to disk
l.write(f)

But in the resulting files, the columns for COMP and DATE are both empty.
Like this:

COMP. : COMPANY
WELL. : WELL
FLD . : FIELD
LOC . : LOCATION
PROV. : PROVINCE
CNTY. : COUNTY
STAT. : STATE
CTRY. : COUNTRY
SRVC. : SERVICE COMPANY
DATE. : DATE
UWI . : UNIQUE WELL ID
API . : API NUMBER

Why is the inserted date and company name not listed?

-

**Comment by bsdis** [comment]
hmmm then im getting: AttributeError: 'OrderedDictionary' object has no attribute 'DATE'

**Comment by kinverarity1** [comment]
Try this?

l.header["DATE"].value = ...

I'm away from a computer at the moment but yes this looks like a bug.



On Sun, Aug 14, 2016 at 11:20 PM +0930, "bsdis" <notifications@github.com<mailto:notifications@github.com>> wrote:


hmmm then im getting: AttributeError: 'OrderedDictionary' object has no attribute 'DATE'

-

**Comment by bsdis** [comment]
That just gives me: KeyError: 'DATE'

This is the code:
l = lasio.LASFile()
l.header['DATE'].value = str(blitztime)

**Comment by kinverarity1** [comment]
Oh of course sorry - header is meant only for read only use. The items are all stored in different sections (Version, Well, Parameters). Try

l.well.DATE = ...



On Mon, Aug 15, 2016 at 4:15 AM +0930, "bsdis" <notifications@github.com<mailto:notifications@github.com>> wrote:


That just gives me: KeyError: 'DATE'

This is the code:
l = lasio.LASFile()
l.header['DATE'].value = str(blitztime)

-

**Comment by bsdis** [comment]
no...
l = lasio.LASFile()
l.well.DATE = str(blitztime)

No errors, but also nothing in the header :/

**Comment by bsdis** [comment]
aha....
l.well['DATE'].value = str(blitztime)
did the trick. We should probably write that in the docs...the example notebooks seems to be outdated then

**Comment by kinverarity1** [comment]
Ok glad it works. Yes the examples are outdated. Probably because I reworked the code for LAS 3 support, one day...



On Mon, Aug 15, 2016 at 2:48 PM +0930, "bsdis" <notifications@github.com<mailto:notifications@github.com>> wrote:


aha....
l.well['DATE'].value = str(blitztime)
did the trick. We should probably write that in the docs...the example notebooks seems to be outdated then

-
