### ISSUE TITLE
Some strings are cast to floats as `inf`

### ISSUE THREAD

**Issue by kwinkunks** [kinverarity1/lasio#146]
A UWI like `300E074350061450` gets cast to `inf` by this code:

https://github.com/kinverarity1/lasio/blob/c4a660b33fa47194cf64e45f3078502ed1ec0a9d/lasio/reader.py#L229-L238

I'll make a PR that fixes it.

**Comment by kwinkunks** [comment]
OK, dammit, I have a bunch of other nonsense in my last push that I don't want to burden you with right now... and I'm not smart enough with git to figure out a PR without those commits. So... I changed those lines in `reader.py` to:

    def num(self, x, default=None):
        if default is None:
            default = x
        try:
            return np.int(x)
        except:
            try:
                x_ = np.float(x)
            except:
                return default
        if not np.isinf(x_):
            return x_
        else:
            return default

And things work for me. We'll go ewith this for now in our project.

**Comment by kinverarity1** [comment]
Thanks! I'll add a test and your fix. Cheers.
