### ISSUE TITLE
removing namedlist dependency

### ISSUE THREAD

**Issue by bsdis** [kinverarity1/lasio#151]
Hi, the namedlist dependency is causing problems with newest anaconda and python 3.6.
Is there any possibility of removing that dependency. I have checked the code, and as far as I can see it is not really used anywhere. It is only imported in las.py but never used. Doing a total search for namedlist gives me the following:

./.travis.yml:29:  - pip install namedlist ordereddict cchardet argparse chardet
./docs/source/install.rst:23:- `namedlist <https://pypi.python.org/pypi/namedlist>`__ - simple and small
./lasio/las.py:36:from namedlist import namedlist
./requirements.txt:2:namedlist

Any possibility of removing it completely?

**Comment by kinverarity1** [comment]
Thanks for checking that - it used to be in there. I have merged the PR into master.
