### ISSUE TITLE
Duplicates first curve on multiple exports

### ISSUE THREAD

**Issue by doiko** [kinverarity1/lasio#211]
When exporting multiple LAS files the command 
lasFile = lasio.LASFile()
do not reinitialize the lasFile, therefore the second file will have duplicate the first curve
~Curves ----------------------------------------------------
MD  .[m]     : RULER
MD  .[m]     : RULER
DT  .[us/f]  : DT

the third triple
~Curves ----------------------------------------------------
MD  .[m]     : RULER
MD  .[m]     : RULER
MD  .[m]     : RULER
DT  .[us/f]  : DT

and so on..

**Comment by doiko** [comment]
Error in my code:)

**Comment by kinverarity1** [comment]
Hey @doiko! Actually might not be in your code. This was a bug - #141 - but it was fixed a few months ago. Make sure you update to the most recent version of lasio with git or with `pip install --upgrade lasio`.

**Comment by doiko** [comment]
Thanks!
I have been strangling with this long time  earlier this year!
Great work.
