### ISSUE TITLE
Warning generated on empty ~Parameter section

### ISSUE THREAD

**Issue by bcnuttall** [kinverarity1/lasio#226]
A warning is generated concerning an empty ~Parameter section: "Header section Parameter regexp=~P was not found." The LAS files in question pass the current version of LAS Certify. There is a ~Parameter section, but there are no parameter lines, only some comment lines. I imagine this issue is related to the regular expression for recognizing the ~Parameter section. I have attached a zipped archive version of an LAS file that illustrates this.

[UT311012308500.zip](https://github.com/kinverarity1/lasio/files/1776188/UT311012308500.zip)

**Comment by dagrha** [comment]
I think this specific error has to do with how sections are read rather than a regex error. 

It appears that lasio looks for lines that start with a `~` and adds any subsequent non-commented lines to the `sect_lines` list of the `read_file_contents` OrderedDict (see [line 289 of reader.py](https://github.com/kinverarity1/lasio/blob/25abedff1ea4d19d41ee88f9bfc9d3f595f0e17a/lasio/reader.py#L289)). 

`sect_lines` remains empty though because lasio doesn't find any lines to add before it hits the next `~`, so `if sect_lines:` (line 290) evaluates to False. Thus the ~P section is never added to the OrderedDict.

**Comment by bcnuttall** [comment]
Thanks. It is just a warning and the routine reads the log. My thought is that lasio should be OK that is OK with LAS Certify. 

Brandon Nuttall

**Comment by kinverarity1** [comment]
Thanks for the issue! Thanks also Dan, I'll work out a way to distinguish between empty and missing sections. The latter certainly needs a warning, the former probably not as it's pretty common.

**Comment by dagrha** [comment]
something along these lines could at least ensure empty sections are added to the OrderedDict (based loosely on [lashead](https://github.com/dagrha/lashead/blob/master/lashead.py#L40)):
```
line = file_obj.readline().strip()
line_number = 0

while not line.upper().startswith('~A'):
    if line.startswith('~'):
        sect_title_line = line
        sect_lines = []
        sect_line_nos = []
        sect_title_line = None
        while True:
            line = file_obj.readline().strip()
            line_number += 1
            if line.startswith('~'):
                sections[sect_title_line] = {
                    "section_type": "header",
                    "title": sect_title_line,
                    "lines": sect_lines,
                    "line_nos": sect_line_nos,
                }
                break
            elif not line.startswith("#"):
                sect_lines.append(line)
                sect_line_nos.append(line_number)

if line.upper().startswith('~A'):
    # use existing code
```
This assumes `~A` is the final section encountered though, which I'm not sure is always the case.

**Comment by bcnuttall** [comment]
I think ~A is typically the last section in LAS 2.0. However, it is possible that some of the LAS 3.0 sections that are data tables similar to ~A could follow.

As far as I remember the CWLS 2.0 standard, the ~V section is required to be first. After that, the ~W, ~P, ~C, and ~O sections are defined, but not necessarily ordered. I think only ~W and ~C are required. You have to have the STRT, STOP, and STEP parameters and the curve descriptions.  The others can be missing or empty. LAS 3.0 basically introduced optional sections for recording other types of downhole data. They kind of expand the specification of the old free form ~O section. 

Brandon Nuttall

**Comment by kinverarity1** [comment]
Yep I want to avoid wherever possible assuming that only data follow ~A.. otherwise LAS 3 support will never happen!

I've fixed this by only raising the warning when the ~ line of a section is actually missing, instead of also when it is empty.

**Comment by bcnuttall** [comment]
Thanks. Several examples in the LAS 3.0 documentation show optional sections following ~A. 

Brandon Nuttall
