### ISSUE TITLE
Multi Threading Reading Returns Empty Data

### ISSUE THREAD

**Issue by toddheitmann** [kinverarity1/lasio#233]
When pooling to get a list of LASFile objects, the threaded objects return empty curve data. The header data is there. Only the numeric curve data is missing.

```python
import glob
from multiprocessing import Pool
import lasio

def get_log_object(path):
    return lasio.read(path)

def main():
    las_files = glob.glob(r'*.las')

    ### read files over loop ###
    print('When Reading In Loop')
    for las_file in las_files[:2]:
        log = get_log_object(las_file)
        print(log.well.uwi.value)
        print(log[0])

    ### pooling multiprocessing ###
    pool = Pool(4)
    logs = pool.map(get_log_object, las_files)
    pool.close()
    pool.join()

    print('When Multiprocessed')
    for log in logs[:2]:
        print(log.well.uwi.value)
        print(log[0])

if __name__ == "__main__":
    main()
```

**Output**
```
When Reading In Loop
35047244830000
[6675.  6675.5 6676.  ... 7287.  7287.5 7288. ]
35047245210000
[5893.  5893.5 5894.  ... 6399.5 6400.  6400.5]
When Multiprocessed
35047244830000
[]
35047245210000
[]
```
Doing 1000+ logs over a single thread loop takes some time. Is there a better way to multithread batch reading of logs? If this is a bug, is there a place to start looking for fixes?

**Comment by kinverarity1** [comment]
Looks like a bug. Maybe try checking id() when multiprocessing, particularly of the CurveItem objects (you would need to look at las_items.py perhaps)?

I'll have a look later this morning.

**Comment by dagrha** [comment]
Just spitballing here, but could this be GIL related? Your list object `logs` is trying to be written to by both threads. Maybe that's why the depth arrays don't get recorded?

By contrast, if the script is written a little differently, namely putting the print statements in the `get_las_object()` function, it appears that multiprocessing the reading of las files with lasio does indeed work:

```
from multiprocessing import Pool
import os
import lasio

def get_las_object(path):
    log = lasio.read(path)
    print(log.well.uwi.value)
    print(log[0])

def main():
    pool = Pool(4)
    path = '\\\\path\\to\\las\\files\\'
    las_files = [os.path.join(path, i) for i in os.listdir(path) if i.lower().endswith('.las')]       
    pool.map(get_las_object, las_files[:2])
    pool.close()
    pool.join()

if __name__ == '__main__':
    main()
```

**Comment by kinverarity1** [comment]
Feels like a bug... I thought map was supposed to work as in Todd's example?

I read somewhere that multiprocessing.Pool.map uses pickle to pass objects back and forth. Maybe there's a problem there?

**Comment by kinverarity1** [comment]
Yep it was a pickling thing. Curve.data was lost when unpickling. I'll do a release later tonight but for now it should be fixed in master.
