### ISSUE TITLE
ValueError: could not convert string to float (for a las file containing time/date with characters)

### ISSUE THREAD

**Issue by krzysztof-slowinski** [kinverarity1/lasio#237]
I am trying to read an example las 2.0 file presented below that contains characters in the time and date formats. Is there a way to handle such cases in the current implementation or is it out of scope because it is not part of the standard?

    ~Version Information
    VERS.             2.0 : CWLS log ASCII standard - Version 2.0
    WRAP.             NO  : One line per depth step
    #
    ~Well Information Block
    #MNEM.UNIT                   Data Type:Information
    #__________________________________________________________
    STRT.           01-JAN-2020 00:00:00 : START INDEX
    STOP.           01-JAN-2020 00:00:01 : STOP INDEX
    STEP.SEC           10.0000 : STEP
    NULL.              -999.25 : NULL VALUE
    COMP.                      : COMPANY
    WELL.                      : WELL
    FLD.                      : FIELD
    LOC.                      : LOCATION
    PROV.                      : PROVINCE
    CNTY.                      : COUNTY
    STAT.                      : STATE
    CTRY.                      : COUNTRY
    SRVC.                      : SERVICE COMPANY
    DATE.                      : LOG DATE
    UWI.                      : UNIQUE WELL ID
    API.                      : API NUMBER
    #
    ~Curve Information Block
    #MNEM.UNIT                     : Curve Description
    #---------                     --------------------
    TIME	    .HHMMSS	       :
    DATE	    .D		       :
    DEPT        .M                 : Bit Depth 2hz
    ARC_GR_UNC_RT.GAPI              : ARC Raw Gamma Ray, Real-Time
    #
    ~Parameter Information Block
    #MNEM.UNIT                       Value:Description
    #__________________________________________________________
    #
    ~Other Information Block

    #
    ~A TIME       DATE       DEPT ARC_GR_UNC_RT
    00:00:00 01-Jan-20  1500.2435        126.56
    00:00:01 01-Jan-20  1500.3519        126.56

**Comment by kinverarity1** [comment]
It’s definitely in scope – my intention was to have lasio read any LAS files without complaint, regardless of what the standards say.

But reading alphanumeric characters in the data section doesn’t work at the moment. It could be done, just need time to implement it – which I don’t have a lot of at the moment ☹

**Comment by krzysztof-slowinski** [comment]
Great! Any plan when it will be published in PyPI?

**Comment by kinverarity1** [comment]
Hopefully later today - thanks for the reminder!
