### ISSUE TITLE
Section Curves should be replaced with Curve

### ISSUE THREAD

**Issue by doiko** [kinverarity1/lasio#246]
According 
[www.cwls.org/wp-content/uploads/2017/02/Las2_Update_Feb2017.pdf](url)
The relative section should be named as "Curve".
Naming it "Curves" prevents some new SW to load lasio exported las files

**Comment by kinverarity1** [comment]
Thanks, I will make the change to "Curve".
________________________________

**Comment by kinverarity1** [comment]
I can't find anything in the standard that specifies what it should be, but a separate issue recently (#239) pointed this out, and I've changed it to "Curve Information" in version 0.21. Does that fix your issue?

**Comment by doiko** [comment]
Thanks,
Now Petrel can open exported Las files
