### ISSUE TITLE
Removing curve from LAS File

### ISSUE THREAD

**Issue by iankitkumar** [kinverarity1/lasio#250]
How can I remove a curve from a LAS file if I accidentally add a curve while creating a LAS file from scratch using lasio. Please reply as soon as possible.

**Comment by kinverarity1** [comment]
You can use the usual Python method for deleting items from a dictionary, with the curve's mnemonic. Or there is a specific method on ``LASFile``.

See the documentation (https://lasio.readthedocs.io/en/latest/lasio.html#lasio.las.LASFile.delete_curve) and also a previous issue #155.
