### ISSUE TITLE
Error if no charset encoding in response headers

### ISSUE THREAD

**Issue by ae3e** [kinverarity1/lasio#259]
hi,

I tried to read a las file from a url in Jupyter.
In the response headers, the ```content-type``` is only ```text/plain```. There's no charset.

Then I got the following error : 

```Python
/opt/conda/lib/python3.6/site-packages/lasio/reader.py in open_file(file_ref, **encoding_kwargs)
     79                 response = urllib.request.urlopen(file_ref)
     80                 encoding = response.headers.get_content_charset()
---> 81                 file_ref = StringIO(response.read().decode(encoding))
     82                 logger.debug('Retrieved data decoded via {}'.format(encoding))
     83         elif len(lines) > 1: # it's LAS data as a string.

TypeError: decode() argument 1 must be str, not None
```

Could it be possible to use the define enconding like this : 
```Python
lasio.read('http://myserver/myfile.las',encoding='windows-1252')
```

**Comment by kinverarity1** [comment]
Could you post a code sample with a URL that is producing the error for you? I am not getting any errors using Python 3.6:

```
Python 3.6.3 |Anaconda, Inc.| (default, Nov  8 2017, 15:12:41) [MSC v.1900 32 bit (Intel)]
Type 'copyright', 'credits' or 'license' for more information
IPython 6.2.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import lasio

In [2]: lasio.__version__
Out[2]: '0.22'

In [3]: !git log --oneline -n 3
2911da1 (HEAD, tag: v0.22) v0.22
1d36ae3 Merge pull request #249 from krzysztof-slowinski/master
fdaccb5 Merge pull request #252 from euclidity/master

In [4]: l = lasio.read('https://raw.githubusercontent.com/kinverarity1/lasio/master/tests/examples/2.0/sample_2.0.las')
```

Thanks for the report!

**Comment by ae3e** [comment]
Unfortunatly, it is a URL on my company's network so I can't give you a code sample with a URL. But, when I request both URLs with Postman, I can see a difference in the response headers which could explain the error : 

Your file : 
![image](https://user-images.githubusercontent.com/12472719/47084052-bc962180-d212-11e8-9ec3-e8e65c1fa48b.png)


My file : 
![image](https://user-images.githubusercontent.com/12472719/47084246-3f1ee100-d213-11e8-829b-6509ac88e62c.png)
