### ISSUE TITLE
ignore_header_errors in add_section() does not function

### ISSUE THREAD

**Issue by KorayKinik** [kinverarity1/lasio#274]
hi! Thanks for the great package. I noticed that the arg 'ignore_header_errors' does not do anything inside the function 'add_section' function in las.py. Not a big problem, but wanted to share.
Many thanks again!

**Comment by kinverarity1** [comment]
Thanks!

It's a bit hidden but it does pass ``ignore_header_errors`` through to this function in ``lasio/reader.py``, via ``sect_kws``:

https://github.com/kinverarity1/lasio/blob/692bc590476f93710f62f7ce9bbe776b65e63c88/lasio/reader.py#L434-L454
