### ISSUE TITLE
Header Attribute API/UWI with Leading Zeros are misread

### ISSUE THREAD

**Issue by sigbikes** [kinverarity1/lasio#278]
Working through a batch of LAS files for Colorado, I am noticing a consistent behavior that may not be working as intended. For every well with a Colorado API number (Example - 05001095820000) the leading zero is dropped. 

Is it just my build that is doing this? 

**Well Information block from example LAS:**
~Version Information
VERS.                      2.0: CWLS Log ASCII Standard - VERSION 2.0
WRAP.                       NO: One line per depth step
~Well Information Block
STRT.FT              1365.0000: 
STOP.FT              8781.0000: 
STEP.FT                 0.5000: 
NULL.                -999.2500: 
COMP.          Windsor Energy Group: COMPANY
WELL.          Christiansen 4-9: WELL
FLD.                   Spindle: FIELD
LOC.           SHL: 1536' FNL & 1123' FWL SW NW--BHL: 662' FNL & 691' FWL NWNW--Sec. 9, Twp. 1S, Rge. 67W: LOCATION
CNTY.                    Adams: COUNTY
SRVC.          PHOENIX SURVEYS, INC.: SERVICE COMPANY
DATE.          Fri Nov 30 03:06:59 2007: LOG DATE
API. 05001095820000           : UNIQUE WELL ID
STAT.                 Colorado: STATE

**Log API Query for Example LAS after import:**
**In[82]:** log.well.API
**Out[82]:** HeaderItem(mnemonic=API, unit=, value=5001095820000, descr=UNIQUE WELL ID)

Regards,

Sig

**Comment by kinverarity1** [comment]
This has come up before (#135) and should have been fixed, but it would be good to confirm whether it has re-emerged. 

What version are you using? (``lasio.__version__``)

**Comment by sigbikes** [comment]
**In[84]:**lasio.__version__
**Out[84]:** '0.23'

**Comment by kinverarity1** [comment]
Thanks! I will look into it.
________________________________

**Comment by dcslagel** [comment]
Here is a propose fix:  
https://github.com/kinverarity1/lasio/pull/288

**Comment by dagrha** [comment]
Fixed with #288. Thank you dcslagel!
