### ISSUE TITLE
Las to Json : includes non-standard json with NaN instead of 'null' in output

### ISSUE THREAD

**Issue by dcslagel** [kinverarity1/lasio#303]
If there are null value entries in a las file when it is translated to json with the standard python json tool, the create 'json' file will contain 'NaN' (Not a Number) entries.  These are invalid JSON.  So JSON parsers throw an error when trying to parse the file.

**Here is an Example:**
Las file
~WELL
...
NULL.            -9999.25 : NULL VALUE
...
~ASCII
   10.00000   -9999.25
   10.50000   -9999.25
   11.00000   -9999.25
   11.50000   -9999.25
   12.00000   -9999.25
   12.50000   -9999.25
   13.00000   -9999.25
   13.50000   -9999.25
   14.00000    5.93302
   14.50000    6.44777

```json
 "SYNTH": [
            NaN,
            NaN,
            NaN,
            NaN,
            NaN,
            NaN,
            NaN,
            NaN,
            5.9330198602237525,
            6.447765520367327,
];
```

**Comment by kinverarity1** [comment]
Hey @dcslagel  - is the correct value for JSON ``null``?

**Comment by kinverarity1** [comment]
@dcslagel assuming ``null`` is correct, could you have a look at #307 to see if it meets your needs?

**Comment by dcslagel** [comment]
@kinverarity1,

Thank you for making this change.  I'll test it and post an update here later next week.

Thanks!,

DC

**Comment by dcslagel** [comment]
@kinverarity1,

I tested this change as follows.  It passed the test so from that perspective it is ready to be merged. 

Below are the steps I used to test it.

1. In Lasio, create a sample_2.0_null.las and output it to sample_2.0_null.json.

```python
import lasio
import json
l = lasio.read("./tests/examples/2.0/sample_2.0_null.las"
with open('sample_2.0_null.json', 'w') as fp: 
    json.dump(l, fp, indent=2, cls=lasio.JSONEncoder) 
```


2. Move the sample_2.0_null.json file into my local install of wellio.js at wellio.js/assets/json_files/lasio_sample_2.0_null.json


3. In Wellio.js
```node
wellio = require('./dist/index.js');
json_file = "assets/json_files/lasio_sample_2.0_null.json";
let lasio_json_str = wellio.read_lasio_json_file(json_file);
let lasio_obj = JSON.parse(lasio_json_str);
let wellio_obj = wellio.lasio_obj_2_wellio_obj(lasio_obj);
wellio_obj.CURVES.ILD[1]) === null;
```

The expected result is that JSON.parse will read the lasio_json_str without throwing an error and that wellio_obj.CURVES.ILD[1] === null is true.  Both of these results occur.

Let me know if I can further assist on this change.

Thank you,
DC

**Comment by kinverarity1** [comment]
Thanks!

**Comment by dcslagel** [comment]
@kinverarity1,

This looks like it was closed before the solution in #307 has been merged.  Is that your intent?

Thanks,
DC

**Comment by kinverarity1** [comment]
Whoops! No, that wasn't the intention. Thanks for picking that up. I've merged the fix now.

**Comment by dcslagel** [comment]
Thanks :-)
