### ISSUE TITLE
Different formatting for depth and rest of data

### ISSUE THREAD

**Issue by MSZeftawy** [kinverarity1/lasio#304]
I really admire the efforts put into this library. Thanks very much.

I have tried to modify writer.py to allow me to get 3 decimals digits for depth and 2 for rest of data. writing it step by step in console works fine, so i modified the writer.py file and as I have no much experience in coding it came out something like this:
`200    for i in range(nrows):`
`201        logger.debug("Writing data array row {} of {}".format(i + 1, nrows))`
`202        depth_slice = ""`
`203        depth_slicea = ""`
`204        depth_sliceb = ""`
`205        depth_slicea = (" "+('%11.3f'%(data_arr[i, 0]))).rjust(1)`
`206        for j in range(1, ncols):`
`207            depth_sliceb += format_data_section_line(data_arr[i, j], fmt)`
`208        depth_slice=depth_slicea+depth_sliceb`

Then I would call it by this line in script
`newlas=open("lastest.las","w")`
`lasio.writer.write(las,newlas,version=2,wrap=None,STRT=None,STOP=None,STEP=None,fmt='%.2f',len_numeric_field=11, data_width=None, header_width=60)`
`newlas.close()`
The output is successfully as intened as following:

> 
```
~ASCII -----------------------------------------------------
       0.000     -999.25     -999.25        0.00        0.00        0.00        0.00        0.00
       1.000     -999.25     -999.25        1.00        0.00        0.00        0.00        0.00
       2.000        1.94      137.49        2.00        0.01       -0.01      138.28        0.02
       3.000        0.71      148.75        3.00        0.03       -0.03      140.46        0.04
       4.000        0.29      144.41        4.00        0.03       -0.04      142.70        0.05
       5.000        0.43      113.12        5.00        0.03       -0.04      140.76        0.05
       6.000        0.74      104.41        6.00        0.04       -0.04      135.69        0.06
       7.000        0.80      104.48        7.00        0.06       -0.05      130.28        0.07
       8.000        0.69      102.56        8.00        0.07       -0.05      126.54        0.08
       9.000        0.69      103.03        9.00        0.08       -0.05      123.87        0.10
      10.000        0.47       96.79       10.00        0.09       -0.05      121.73        0.10
```
> 

Which will work fine for my needs.

Could you please consider modifying the writer to include fmt for depth separately?

Thanks again.

Regards
Moustafa

**Comment by kinverarity1** [comment]
Thanks Moustafa, I'll have a look for how we might be able to incorporate this. Cheers, Kent.
________________________________

**Comment by MSZeftawy** [comment]
Hi Kent,
Thanks for the quick response. I am interested to help. Just let me know how. 
Cheers, 
Moustafa

**Comment by kinverarity1** [comment]
Hey @MSZeftawy - would you be able to have a look at #306 and see if that example meets your needs? If it does, I will merge it into master.

**Comment by MSZeftawy** [comment]
Hey Kent,
It perfectly does. Please merge it into master.
Cheers
Moustafa
