### ISSUE TITLE
Request for new Lasio pip release : 0.24.2?

### ISSUE THREAD

**Issue by dcslagel** [kinverarity1/lasio#309]
@kinverarity1

Could a new release of Lasio  be packaged and posted for use with pip?  The reason for this request is to pick up the new Json 'null' output feature in a python/pip package.   

I would be happy to assist with this if you would like.  (I would need instructions for the release steps).

Thank you,
DC

**Comment by kinverarity1** [comment]
Yikes, it's been ages. Yes I will do one today.

**Comment by kinverarity1** [comment]
Should be on PyPI and GitHub here: https://github.com/kinverarity1/lasio/releases/tag/v0.25.0

**Comment by dcslagel** [comment]
Thanks!  I updated to 0.25.0 with pip.

DC

**Comment by ThomasMGeo** [comment]
Thanks everyone, upgraded this morning with pip and had zero issues.

-TM
