### ISSUE TITLE
delete_curve issue

### ISSUE THREAD

**Issue by hflesche** [kinverarity1/lasio#315]
If you loop through curves in a las-file to delete some of them, the result is not correct unless you start from the last curve and move forwards. Let's say we have a las object with curves DEPTH, BS, CALI, RHOB, DT and DTS. The following code will skip CALI when BS curve is deleted:

```
keep_curves = ['DEPTH', 'DT', 'DTS']
for curve in las_file.curves:
    if curve.mnemonic not in keep_curves:
        las_file.delete_curve(curve.mnemonic)
```
whereas if the list of curves is reversed, the correct ones are deleted:
```
use_curves = ['DEPT', 'DT', 'DTS']
for curve in reversed(las_file.curves):
    if curve.mnemonic not in keep_curves:
        las_file.delete_curve(curve.mnemonic)
```

**Comment by kinverarity1** [comment]
Thanks @hflesche, I will have a look at this tomorrow.

**Comment by kinverarity1** [comment]
I have a feeling this is always likely to fail, e.g. https://stackoverflow.com/a/2897058/596328

Out of curiosity, does adding a slice to obtain a copy (see below) work for you?

```python
keep_curves = ['DEPTH', 'DT', 'DTS']
for curve in las_file.curves[:]:
    if curve.mnemonic not in keep_curves:
        las_file.delete_curve(curve.mnemonic)
```

**Comment by hflesche** [comment]
Yes, that works. Another option that also works is this:
```
for curve_name in las_file.keys():
    if curve_name not in keep_curves:
        las_file.delete_curve(curve_name)
```

According to the link that you sent, this may not be an issue for delete_curve, it is more of a Python issue. A warning could perhaps be added to the docs, but it is not really a bug.

**Comment by kinverarity1** [comment]
Great idea, I'll add something to the docs!
________________________________
