### ISSUE TITLE
EOF Error causes np.reshape errors.

### ISSUE THREAD

**Issue by ahype-loves-geoscience** [kinverarity1/lasio#321]
\x1a is a common marker in forigen LAS files. 

Files with eof marker of '\x1a' cause lasio read to fail. 

with open(row.filename) as file:
    lines = file.readlines()

print(lines[-2:])

[' 3849.9290 -999.2500 -999.2500 -999.2500 -999.2500 -999.2500 -999.2500 -999.2500 -999.2500\n', '\x1a']

If I remove it the files load. I found a quick fix of checking if the line start with \x1a but I'm hoping there is more elegant way of doing it.

**Comment by kinverarity1** [comment]
Thanks for reporting this. I'll look into it.

**Comment by kinverarity1** [comment]
Oh, GitHub closed it automatically - please let me know if that doesn't fix your issues @ahype-loves-geoscience  and @ThomasMGeo
