### ISSUE TITLE
Reshape issue.

### ISSUE THREAD

**Issue by ThomasMGeo** [kinverarity1/lasio#323]
Hi Kent et al.

This .las file does not want to read in, it seemed to have some weird unicode at the end of it. Is there a way to not read that in? Attached is the offending file. Once I removed it, read in just fine.

Zipped to make github happy.
[4900722364_722364A.las.zip](https://github.com/kinverarity1/lasio/files/4562580/4900722364_722364A.las.zip)

-TM

**Comment by kinverarity1** [comment]
duplicate of #321
