### ISSUE TITLE
Python 2.7 support and sunsetting schedule

### ISSUE THREAD

**Issue by dcslagel** [kinverarity1/lasio#364]
Python.org stopped supporting Python 2.7 in January.  
https://www.python.org/doc/sunset-python-2/

How long will Lasio continue Python 2.7 support?

**Comment by kinverarity1** [comment]
I'm happy to drop it once we need to. Looks like we'll need to for the work going into #327 but once that's merged, python 2.7 will no longer be supported.

In terms of releases, I'll so another minor release immediately before #327 is merged, so that will be the final release for 2.7.

**Comment by dcslagel** [comment]
There are 75 projects (by GitHubs count) that depend on Lasio.  It might be good to put an 2.7 sunsetting notice at the top of the README.md so other projects are aware and can make any needed adjustments.

**Comment by kinverarity1** [comment]
Good idea. I guess there will be a couple things:

- add sunsetting notice to readme (do now)
- wait until #327 is ready
- tag a new minor release which will serve as the last python 2.7 release. We can backport critical fixed into this version number.
- create long term `py27` branch (?)
- merge some changes to `master` to remove python 2.7 support:
  - add a `python_requires` for 3+ to `setup.py`
  - update qualifiers in `setup.py`
  - remove Travis 2.7 tests
  - update readme and sphinx docs
- merge #327 

Anything else I'm missing?

**Comment by dcslagel** [comment]
Thats a good list.  It looks thorough.  :-)

**Comment by kinverarity1** [comment]
I'm not sure why I targeted a separate branch. If it gets to a point where all tests are passing, I'll merge it into master.

**Comment by kinverarity1** [comment]
Great work with #327! I've re-targeted the latter to `master` and once I get around to doing the relevant steps above, hopefully this weekend, I'll merge it.

**Comment by dcslagel** [comment]
@kinverarity1, great, that's a good plan. thanks for the update. 

 The master branch has 71 commits and 17 additional tests since rearrange-reader initially forked.  I'm going to make some rr_rebase_(x) branch(s) to attempt the rebase from master to rearrange-reader.

**Comment by dcslagel** [comment]
Rebase findings:
- I wasn't able to make a rebase branch that you could merge to rearrange-reader and then to master without conflicts.  So not posting a branch
- There are just 2 conflicts
   - tests/test_read.py  (Take the master branch changes)
   - tests/test_read_30.py (Take the rearrange-reader changes)
- Reviewing the code after rebasing everything looked okay.
- You should see good post-rebase test-coverage results.  This is what my local post-rebase results are:
220 passed, 3 skipped
```
Name                       Stmts   Miss  Cover
----------------------------------------------
lasio/__init__.py             13      2    85%
lasio/convert_version.py      20     20     0%
lasio/defaults.py             11      0   100%
lasio/examples.py             42     10    76%
lasio/excel.py                88     34    61%
lasio/exceptions.py            6      0   100%
lasio/las.py                 376     55    85%
lasio/las_items.py           190     31    84%
lasio/las_version.py          34     22    35%
lasio/reader.py              437     84    81%
lasio/writer.py              160      9    94%
----------------------------------------------
TOTAL                       1377    267    81%
```

**Comment by kinverarity1** [comment]
#364 (removal of Python 2.7 support in theory and from CI testing) and #327 (removal of ability to run using Python 2.7) have been merged to master.

Thanks @dcslagel for raising this in the first place, and everyone for their patience 😉
