### ISSUE TITLE
Lasio is writing the python None object to the string 'None' when writing HeaderItems to a file

### ISSUE THREAD

**Issue by dcslagel** [kinverarity1/lasio#377]
Lasio is writing the python None object to the string 'None' when writing to a file.  Subsequent Lasio.read(<new.las>) will set the HeaderItems value field to the string 'None' rather than the python NoneType object.  

#### Possible solution:
If we write nothing, lasio.read(...) will interpret that as a empty string "".  That would be more correct than 'None' because an empty string is a more common and standard object than a 'None' string. Particularly if the new las file is read by other software. 

Potentially lasio.read() could be changed to transform all HeaderItem empty string values to NoneType objects. That seems to make sense. However, could it have an impact on current apps that use Lasio?

**Comment by dcslagel** [comment]
#### Example code to demonstrate the problem

```python
import lasio
las = lasio.read('tests/examples/2.0/sample_2.0.las')

#------------------------------------------------------------------
headerTD = lasio.HeaderItem()
headerTD.mnemonic = 'TD'
headerTD.value = None
las.sections['Parameter'].append(headerTD)       

print("Org value of TD value: ", end="")
print(headerTD.value)
print("Is it really None? : ",  las.params.td.value == None)
print("Org Type of TD value: {}".format(type(headerTD.value)))
#------------------------------------------------------------------


mytofile = "myto.las"
las.write(mytofile, version=2.0)

newlas = lasio.read(mytofile)

print("New value of TD value: ", end="")
print(newlas.sections['Parameter']['TD'].value)
print("Is it really None? : ", newlas.params.td.value == None)
print("New type of TD value: {}".format(type(newlas.params.td.value)))

```

**Comment by kinverarity1** [comment]
I think we should write `None` as an empty string, and continue to read blank values as empty strings, for all HeaderItems.

To fix I guess we could wrap `item.value` in a function `lambda v: "" if v is None else str(v)`:

https://github.com/kinverarity1/lasio/blob/bd42e823653966472c2e2cca29163ed3e5a602f3/lasio/writer.py#L277-L288

**Comment by dcslagel** [comment]
Draft fix is posted at https://github.com/kinverarity1/lasio/pull/378

**Comment by kinverarity1** [comment]
#378 has been merged to `master`
