### ISSUE TITLE
Python 3 issue with version 0.5 was working with the previous version

### ISSUE THREAD

**Issue by VelizarVESSELINOV** [kinverarity1/lasio#38]
This line `` from las_reader import read`` is creating exception as shown below:

```
Mac:~/GitHub/las-reader (original)/las_reader$ pip install las-reader --upgrade
Collecting las-reader
  Downloading las_reader-0.5-py2.py3-none-any.whl
Collecting namedlist (from las-reader)
  Downloading namedlist-1.7.tar.gz
Collecting numpy (from las-reader)
  Downloading numpy-1.9.2-cp34-cp34m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (3.7MB)
    100% |████████████████████████████████| 3.7MB 158kB/s 
Installing collected packages: namedlist, numpy, las-reader
  Running setup.py install for namedlist
  Found existing installation: las-reader 0.0.0
    DEPRECATION: Uninstalling a distutils installed project (las-reader) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling las-reader-0.0.0:
      Successfully uninstalled las-reader-0.0.0
Successfully installed las-reader-0.5 namedlist-1.7 numpy-1.9.2
Mac:~/GitHub/las-reader (original)/las_reader$ python3
Python 3.4.3 (v3.4.3:9b73f1c3e601, Feb 23 2015, 02:52:03) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from las_reader import read
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/las_reader/__init__.py", line 3, in <module>
    from las import __version__, LASFile, Curve, HeaderItem
ImportError: cannot import name '__version__'
>>> 
```
I think there is something wrong with the latest Python 3 commit. It will be great to have some automatic tests before the version is pushed to pip.

**Comment by kinverarity1** [comment]
I agree that an automatic test suite would be excellent - a PR would be welcome.

**Comment by diverdude** [comment]
Interesting. This is the exact same error i got before i made those changes.
Basically that is what i fixed by chaning the way the import was done in
the __init__.py file
For me it works great in python 3 now.


On Mon, Aug 3, 2015 at 1:43 PM, Kent Inverarity <notifications@github.com>
wrote:

> I agree that an automatic test suite would be excellent - a PR would be
> welcome.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kinverarity1/las-reader/issues/38#issuecomment-127205641>
> .
>



-- 
Med venlig hilsen
Bjørn Skovlund Dissing

**Comment by diverdude** [comment]
I just tried installing from repo and comparing the __init__ file with the
__init__ file in my PR, and that __init__ file in the pip installed version
does not have my changes.
Did you remember to merge in the branch i made the changes in when u
completed the PR kinverarity?

(P.S. i also get that error when running P3 version from pip installed
version, so i am guessing something went wrong in the merge - basically it
should be from .las import blabla and not from las import blabla)

On Mon, Aug 3, 2015 at 2:31 PM, Bjørn Dissing <bjorndissing@gmail.com>
wrote:

> Interesting. This is the exact same error i got before i made those
> changes.
> Basically that is what i fixed by chaning the way the import was done in
> the __init__.py file
> For me it works great in python 3 now.
>
>
> On Mon, Aug 3, 2015 at 1:43 PM, Kent Inverarity <notifications@github.com>
> wrote:
>
>> I agree that an automatic test suite would be excellent - a PR would be
>> welcome.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/kinverarity1/las-reader/issues/38#issuecomment-127205641>
>> .
>>
>
>
>
> --
> Med venlig hilsen
> Bjørn Skovlund Dissing
>



-- 
Med venlig hilsen
Bjørn Skovlund Dissing

**Comment by kinverarity1** [comment]
Whoops, that was indeed my mistake in merging on Github and not pulling the latest version before creating the distribution for pypi.

I'll take a little more care with pushing upates to pypi. Thanks for raising the issue Velizar and for fixing the original problem diverdude.

**Comment by VelizarVESSELINOV** [comment]
Let me know when you have updated package on PyPI, I can test it very quickly.

**Comment by VelizarVESSELINOV** [comment]
Problem solved, working again as expected :+1:
