### ISSUE TITLE
Parse unit starting with dot

### ISSUE THREAD

**Issue by eimerej** [kinverarity1/lasio#402]
I have Las with unit starting with dot:
```TDEP    ..1IN          :0.1-ft Frame Depth {F13.4}```

In this case, the first dot is part of the mnemonic instead of the unit.
This is a special behavior implemented in lasio to support '..' caused by mnemonic abbreviation.
From the function *configure_metadata_patterns(line, section_name)*

```py

if ".." in line and section_name == "Curves":
   # ...
    name_re = name_with_dots_re
```

According to the standard (2.0 and 3.0) mnemonic should not contains dot but unit could.

I see two way of solving this issue:
1. follow the standard and do not use the `name_with_dots_re` regexp
2. if there is some space between the mnemonic and the first dot assume that the dot belong to the unit and not to the mnemonic:
  ```py
  # replace
  if ".." in line and section_name == "Curves":
  #  by something like that
  if re.search('[^ ]\.\.', line) and section_name == "Curves":
  ```

**Comment by kinverarity1** [comment]
Hi @eimerej thank you for raising this issue! Excellent points, and thank you for the PR also!

**Comment by dcslagel** [comment]
Hi @eimerej, @kinverarity1 ,

In your file with `TDEP ..1IN :0.1-ft Frame Depth {F13.4}`  what is the ~WELL INFORMATION section's STRT line?  Is the unit also `.1IN` there?  Could that be used to decide whether the following example has a unit of `1IN` or `.1IN`?
Example: `I. Res..1IN                      : `

Thanks,
DC

**Comment by dcslagel** [comment]
Hi @eimerej, @kinverarity1,

Just thinking through the various scenarios.  While Lasio doesn't currently parse all of these in the following (expected?) ways, 1 - 4 are do-able with just the information in a given metadata line.  Number 5 show situations where how to parse it is ambiguous.

1. `TDEP ..1IN :0.1-ft Frame Depth {F13.4}`
- This could parse clearly  as Name = 'TDEP', Unit = .1
- Pattern [space][dot-delimiter][unit]

2. `TDEP.. 1IN :0.1-ft Frame Depth {F13.4}`
- This could parse clearly  as Name = 'TDEP.', Unit = 1
- Pattern [abbreviation-dot][dot-delimiter][unit]

3. `TDEP. . .1IN :0.1-ft Frame Depth {F13.4}`
- This could parse clearly  as Name = 'TDEP.', Unit = .1
- Pattern [abbreviation-dot][space][dot-delimiter][space][unit]

4. `TDEP...1IN :0.1-ft Frame Depth {F13.4}`
- This could parse clearly  as Name = 'TDEP.', Unit = .1
- Pattern [abbreviation-dot][dot-delimiter][unit]

5. `TDEP..1IN :0.1-ft Frame Depth {F13.4}`
and
`TDEP. .1IN :0.1-ft Frame Depth {F13.4}`
- These cases are ambiguous as to how to parse Name and Unit


DC

**Comment by kinverarity1** [comment]
Sorry about the delay on getting to this issue, it's a tricky one! @dcslagel  I think your points 1 through 5 above are correct. I'm not fussed about how to parse example 5 - whatever the parsing spits out seems reasonable.

@dcslagel  How would you like me to proceed with #413?

**Comment by dcslagel** [comment]
Hi @kinverarity1,

Okay, this is good feedback!  Thanks.   I've been mulling over how to implement handling these in code.  I hope to work on it in the next couple of weeks.

DC

**Comment by dcslagel** [comment]
Hi @eimerej,

The initial example in this issue `TDEP ..1IN :0.1-ft Frame Depth {F13.4}`, is it missing a value field?  Is your expectation that this line should parse into fields like so:
name == "TDEP"
unit == ".1IN"
value == ""
descr == "0.1-ft Frame Depth {F13.4}"

Thanks,
DC

**Comment by eimerej** [comment]
Hi @dcslagel,
Yes, there is no value in this case.

**Comment by dcslagel** [comment]
Just a quick update,  I'm still working on this, just delayed with other activities..
DC

**Comment by dcslagel** [comment]
Hi @eimerej , @kinverarity1 ,

After spending a fair amount of time looking that this, it seems to me that @eimerej 's solution in pull-request https://github.com/kinverarity1/lasio/pull/403  is the right one for now.   It takes care of the cases #1 and #2 that I listed above and the cases #3 and #4 are highly unlikely and can be solved if there is ever a real-world case reported.  Case #5, @kinverarity1 , mentioned it is okay to let it resolve with the current logic in Laisio.

So all that said, I encourage merging pull request #403.  Thank you for allowing me to dig in to this problem for a while.

DC
