### ISSUE TITLE
file stays in memory / doesn't close?

### ISSUE THREAD

**Issue by danomics-cam** [kinverarity1/lasio#409]
I'm not sure what is going on exactly, but I suspect that files are being kept in memory.  When reading a large number of files (~1000 files) in a loop for example:

```python
i = 0
for file in file_list:
    file2read = mypath + '//' + file
    las = lasio.read(file2read)
    lasDF=las.df()
    myIndex = lasDF.index
    lasDF['DEPTH'] = myIndex
    lasDF['LIN_RES'] = np.log(lasDF['RESD_FINAL'])
    output = np.concatenate((output, lasDF), axis=0)
    i+=1
    print(i/len(file_list)*100, "% complete. Read: ", file)
```

The memory usage seems to continuously climb.  Is there a file.close() that needs to be performed by the user?

**Comment by kinverarity1** [comment]
Sounds dodgy - thanks for reporting. Can you confirm the version of lasio you are using with `lasio.__version__`?

**Comment by danomics-cam** [comment]
Version is: '0.24.1'
Some add'l info if it makes any difference:
OS: Windows 10; 16GB Ram
Total LAS file count: 1464
Total LAS input file size: 1.21 GB
I'm wondering if it's not getting stuck in the python garbage collector.  For example I just ran about 455 files through and checked the gc.get_count() and it's at (557,6,1), so might not be a lasio issue, but a setting on my side.

**Comment by danomics-cam** [comment]
Yeah, I'll run overnight and check back in.

**Comment by kinverarity1** [comment]
Thanks!

**Comment by danomics-cam** [comment]
Okay, ran a couple of different tests.  It's not an issue with LASio. What was happening was that one of my subsequently created DFs was making a recursive slice of itself without me realizing that (so I had 1464 dataframes open -- oops).
