### ISSUE TITLE
Time-indexed LAS file

### ISSUE THREAD

**Issue by LuisNavarro93** [kinverarity1/lasio#416]
Is there a way to import .las file with Date-Indexed data??
![image](https://user-images.githubusercontent.com/62827729/103789972-3c805000-5006-11eb-9e8f-b322aa58f1b5.png)
The LAS file structure goes as follows.
![image](https://user-images.githubusercontent.com/62827729/103790225-8b2dea00-5006-11eb-936b-efc1a5a315b1.png)
![image](https://user-images.githubusercontent.com/62827729/103790273-9a149c80-5006-11eb-9a0e-015f3bc52b65.png)

**Comment by kinverarity1** [comment]
Thanks for raising this issue. It's not possible at the moment, but will be part of LAS 3.0 support when we implement that.

**Comment by LuisNavarro93** [comment]
Thank u... Looking forward to the release

**Comment by kinverarity1** [comment]
Could you please try this again with lasio v0.30?

It should now work: https://lasio.readthedocs.io/en/v0.30/data-section.html#handling-text-dates-timestamps-or-any-non-numeric-characters
