### ISSUE TITLE
Have an issue with urllib2 when using the lasio package

### ISSUE THREAD

**Issue by jaymathe** [kinverarity1/lasio#426]
We see that urllib2 is being used in this file: https://github.com/kinverarity1/lasio/blob/4adc6d6312ae743df513da8e8e5a49495adbb297/lasio/reader.py#L96
We seem to run into an issue when running the package on a Python 3.6: 
https://stackoverflow.com/questions/2792650/import-error-no-module-name-urllib2

**Comment by dcslagel** [comment]
Hi @jaymathe,

This may have been fixed by pull-request #428 "Update urllib.request to be the preferred urllib", which is now merged.  If you are working with the GitHub source, could you update to the latest Lasio code and see if this issue is not resolved?

Thank you,
DC

**Comment by kinverarity1** [comment]
Closing this as it should be fixed now with the latest code on GitHub. @jaymathe if you continue to find issues please feel free to reopen.
