### ISSUE TITLE
Using python 2 to read LAS 3.0 - ValueError: cannot reshape array of size 162549 into shape (52)

### ISSUE THREAD

**Issue by RodrigoBCC** [kinverarity1/lasio#433]
I need some help, when i read file LAS 3.0(like bellow):

`las = lasio.read("/usr/src/app/uploads/Fake/Log/CompositeProfile/teste.las")`

Returns erro: **ValueError: cannot reshape array of size 162549 into shape (52)**

**Comment by kinverarity1** [comment]
Hi @RodrigoBCC 

- can you upload an example file which gives you this error?
- What version of lasio are you using? (`import lasio; print(lasio.__version__)`)
- What version of Python are you using?

Also in case you are not aware lasio does not properly support LAS version 3 yet.

**Comment by kinverarity1** [comment]
Closing until we get more information.
