### ISSUE TITLE
Provide a way to benchmark speed performance of `LASFile.read`

### ISSUE THREAD

**Issue by kinverarity1** [kinverarity1/lasio#444]
**Is your feature request related to a problem? Please describe.**
This is subjective, but I think it's fair to say `LASFile.read` is too slow. Compared to the performance that parsing a similarly-sized table using `pandas.read_csv`, it is very obviously slow. One of the big problems in improving this is the lack of reliable benchmarks to ensure we are improving performance.

**Describe the solution you'd like**
A simple way to see the performance of `LASFile.read` for one branch compared to another branch, in a reliable way. Then we can try out different code in attempts to improve the performance and see whether we're getting anywhere!

**Describe alternatives you've considered**
I've tried doing profiling locally but I've found depending on what else is happening on my machine at the time, the speeds vary quite widely. I also have no experience in setting up this kind of thing so am keen for any ideas.

** Solution **

- [x]  PR #449 implements a benchmark
- [ ] Add description of how to compare benchmarks to Sphinx documentation
- [ ] Set up CI benchmarks somehow

**Comment by kinverarity1** [comment]
Implemented in #449 but could be improved - I've added a checklist to the issue description above.

**Comment by dcslagel** [comment]
How about we move the checklist items to each be an issue.  The benefit is that they will be visible  and track-able at the issue level.

**Comment by kinverarity1** [comment]
Yep good idea I'll do that 👍

**Comment by kinverarity1** [comment]
See #457 and #458 for remaining tasks. Closing this one.
