### ISSUE TITLE
Missing value management on the reference curve

### ISSUE THREAD

**Issue by VelizarVESSELINOV** [kinverarity1/lasio#45]
If `NULL` is setup as 0, and the LAS file have reference DEPTH with value 0, today the library is replacing the value with `nan` for all the Curves, I know some other software packages that do this only for curves that are not reference.

LAS specification document is not very clear about how should be managed reference with `NULL` value, but I found it more logical to keep the reference without `NULL` replacement.

What do you think?

**Comment by kinverarity1** [comment]
I think your suggestion should be the default, with a keyword argument to control whether a substitution is made everywhere or not at all or with a different value to ``nan``.




On Tue, Aug 4, 2015 at 2:15 AM -0700, "Velizar VESSELINOV" <notifications@github.com> wrote:
If ``NULL`` is setup as 0, and the LAS file have reference DEPTH with value 0, today the library is replacing the value with ``nan`` for all the Curves, I know some other software packages that do this only for curves that are not reference.

LAS specification document is not very clear about how should be managed reference with ``NULL`` value, but I found it more logical to keep the reference without ``NULL`` replacement.

What do you think?

---
Reply to this email directly or view it on GitHub:
https://github.com/kinverarity1/las-reader/issues/45

**Comment by kinverarity1** [comment]
In light of #49 this could be a keyword argument ``index_null_replacement`` which is ``False`` by default.

**Comment by kinverarity1** [comment]
This issue is the same as #227 - which is now fixed!
