### ISSUE TITLE
rounding issues when writing las file

### ISSUE THREAD

**Issue by eucalypt1** [kinverarity1/lasio#453]
When saving a lasfile using las.writer(filename, version=2),  the following well items show as shown below:
STRT.M              1240.0 : START DEPTH
STOP.M  1258.1999999999834 : STOP DEPTH
STEP.M 0.09999999999990905 : STEP

No matter the date frame data or what I specify prior to running las.writer, the data shows as above. I try to show them as:
STRT.M              1240.0 : START DEPTH
STOP.M             1258.2  : STOP DEPTH
STEP.M                  0.10 : STEP

Also, when creating a lasfile using:  las = lasio.LASFile() and try to save it later with las.writer, if the other sections (Curves, Params and the actual data values (below ~ASCII) are not filled, the las,writer returns an exception. I use visual studio  (if that plays a role in this issue)

Thanks for all your work.

**Comment by dcslagel** [comment]
Hi @eucalypt1,   

What Lasio version are you using?

Could you include a minimum code example that reproduces the problem you are seeing with las.writer()?

Thank you

**Comment by eucalypt1** [comment]
Hi  According to Anaconda, I have version 0.28.  I just pushed the update button, but it seems to be the newest.      #Create Las ASCII file    #First create the DEPT curve    for c_idx in range(mend):        #mnemonic=cdescrvs[c_idx]        new_cas.insert_curve(ix=c_idx, mnemonic=cdescrvs[c_idx], data=np.array(mlist[c_idx]),                            unit= c_units[c_idx], descr=c_descr[c_idx],                             value='')     # ready to save cas file    filename=UWI+'.las'    save_las(filename,new_las)   def save_las(filename,new_las):    if (Indir != Rawdir):        # check if Indir selected        if Indir:            # Now save            data_folder = Path(Indir)            new_Path = data_folder/filename            new_File = str(new_Path)            new_laswrite(new_File, version=2.0)            root.update_idletasks()        else:            c_Error('No Output Directory selected - select in File menu')    elif not Infile:        c_Error('Output must differ from Raw directory - Select in File menu')  Sent from Mail for Windows 10 From: DC SlagelSent: Monday, April 19, 2021 12:39 PMTo: kinverarity1/lasioCc: eucalypt1; MentionSubject: Re: [kinverarity1/lasio] rounding issues when writing las file (#453) Hi @eucalypt1,What Lasio version are you using?Could you include a minimum code example that reproduces the problem you are seeing with las.writer()?Thank you—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe. 

	
        
		Virus-free. www.avast.com

**Comment by dcslagel** [comment]
Hi @eucalypt1 ,  

This is being worked on in pull-request #455.  You can track the progress there.

DC

**Comment by kinverarity1** [comment]
Hi @eucalypt1 

@dcslagel has written a fix for your issue which has now been included in the `master` branch on GitHub. I will post here when I have released a new version of lasio which includes the fix, hopefully soon but has not been done yet. Please let us know if you find the issue remains for you, and feel free to re-open this GitHub issue.

**Comment by eucalypt1** [comment]
Thank you  Sent from Mail for Windows 10 From: Kent InveraritySent: Friday, April 23, 2021 9:23 PMTo: kinverarity1/lasioCc: eucalypt1; MentionSubject: Re: [kinverarity1/lasio] rounding issues when writing las file (#453) Hi @***@***.*** has written a fix for your issue which has now been included in the master branch on GitHub. I will post here when I have released a new version of lasio which includes the fix, hopefully soon but has not been done yet. Please let us know if you find the issue remains for you, and feel free to re-open this GitHub issue.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe. 

	
        
		Virus-free. www.avast.com
