### ISSUE TITLE
Data taken as row indices when converting to pandas DataFrame

### ISSUE THREAD

**Issue by thoerbr** [kinverarity1/lasio#476]
**Describe the bug**
When running e.g. the example or importing a custom .las file and using the pandas.DataFrame integration, the first row of data (DEPT) is taken as row indices.

**To Reproduce**
```
import lasio.examples
las = lasio.examples.open('6038187_v1.2.las')
df = las.df()
df['DEPT']
```

**Expected behavior**
DEPT should be the first column and should be accessible with `df['DEPT']`
A suggested workaound until fixed:
`df['DEPT'] = df.index.values`

**Comment by kinverarity1** [comment]
Hi Thorsten,

Thanks for the report. This is by design, see the documentation at https://lasio.readthedocs.io/en/latest/pandas.html

You can have the first curve in the dataframe accessible as ``df['DEPT']`` by using ``df = las.df().reset_index()``. I'll add that to the documentation.
