### ISSUE TITLE
Add the GitHub topic 'lasio' to the topic tags in the About section of kinverarity1/lasio

### ISSUE THREAD

**Issue by dcslagel** [kinverarity1/lasio#494]
**Describe the solution you'd like**
Add the GitHub topic 'lasio' to the topic tags in the About section of https://github.com/kinverarity1/lasio

**Additional context**
'lasio' is now a topic on GitHub see: https://github.com/topics/lasio.  There are currently 6 entries.  2 look to be related to Lidar rather than Log-Ascii-Standard.  The other 4 are related to Log-Ascii-Standard.  It seems like lasio should be there too.

If this doesn't seem appropriate, this issue can be closed.

Thank you,
DC

**Comment by kinverarity1** [comment]
Good catch, that's so strange that "lasio" is a topic and yet not on the list! I've added it now. Thanks!
