### ISSUE TITLE
NumPy type conversion alias deprecation

### ISSUE THREAD

**Issue by kwinkunks** [kinverarity1/lasio#502]
**Describe the bug**
Two type conversions in `lasio` v0.29 are throwing warnings for me in Python 3.9 / NumPy 1.21.4:

> lib/python3.9/site-packages/lasio/reader.py:709: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
  Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

**To Reproduce**
Not sure... I get the warnings (9800 of them!) when I run welly's tests... but not when I load a well in lasio. Does pytest somehow show me more warnings? Not sure.

**Expected behavior**
No warnings

**Software versions (please complete the following information):**
 - Python version: 3.9, 64-bit
 - Python distribution: Miniconda
 - Lasio: 0.29
 - NumPy 1.21.4

**Additional context**

**Comment by kinverarity1** [comment]
Thanks Matt
