### ISSUE TITLE
Add automated testing status per branch from CI external tool

### ISSUE THREAD

**Issue by VelizarVESSELINOV** [kinverarity1/lasio#51]
Please find some examples of status flags:
http://docs.travis-ci.com/user/status-images/
http://stackoverflow.com/questions/14274293/show-current-state-of-jenkins-build-on-github-repo

**Comment by kinverarity1** [comment]
Yes! Will set it up as soon as I can. Great services.

**Comment by kinverarity1** [comment]
Done.

See build test results for Python 2 and 3 at https://travis-ci.org/kinverarity1/lasio

And see test coverage at https://coveralls.io/github/kinverarity1/lasio

**Comment by kinverarity1** [comment]
The build is failing because reading direct from a URL is failing on Python 3 for some reason presumably to do with encodings -- I've opened #55

**Comment by kinverarity1** [comment]
https://raw.githubusercontent.com/RazerM/odmpy/master/README.md
