### ISSUE TITLE
Update PYPI description of the package

### ISSUE THREAD

**Issue by VelizarVESSELINOV** [kinverarity1/lasio#54]
Still no mention about writing on PyPI: https://pypi.python.org/pypi/lasio/0.6. Probably you need to update it.
```
lasio 0.6
Read borehole data from Log ASCII Standard (LAS) files
A library for reading borehole data from log standard ASCII (LAS) files (only specifications 1.2 and 2.0 are supported for now).
Keywords: science geophysics io
```

When you think (or what it is needed) the package will move from ``Beta`` to ``Production/Stable``?

**Comment by kinverarity1** [comment]
I would prefer to have a relatively comprehensive test suite before incrementing the version to 1.0. That is the point where I'll change PyPI status to Production/Stable. Otherwise I can't really promise stability.
