### ISSUE TITLE
Update the "Building a LAS file from scratch" doc for current usage.

### ISSUE THREAD

**Issue by dcslagel** [kinverarity1/lasio#541]
**Describe the bug**
Update the "Building a LAS file from scratch" doc because las.add_curve() nolonger exists and is replaced with las.append_curve()

**To Reproduce*
   File: docs/source/building.rst

**Expected behavior**
- The document should explain how to build an LAS file from scratch using the current functions.

**Software versions (please complete the following information):**
 - Python version: 3.9
 - Python distribution: Homebrew
 - lasio version: 0.31

**Additional context**
n/a

**Comment by dcslagel** [comment]
This fix is available on the `latest` main-branch of the documentation:
https://lasio.readthedocs.io/en/latest/

**Comment by dcslagel** [comment]
@kinverarity1 , Continuing the discussion from issue # https://github.com/kinverarity1/lasio/issues/561 about when to close issues. What is your thinking on this one?

**Comment by kinverarity1** [comment]
Same, I think - I'd probably close this and make a note once it's released.

Probably time to make a release!

**Comment by kinverarity1** [comment]
Of course, no problem
