### ISSUE TITLE
End Lasio support for Python 3.5 and 3.6 ?

### ISSUE THREAD

**Issue by dcslagel** [kinverarity1/lasio#549]
#### Description
Python 3.5 and 3.6 are considered end-of-life at python.org.  Is it time for Lasio to end official support for them also?

- Python 3.6.15: Release Date: Sept. 4, 2021
Note: The release you are looking at is Python 3.6.15, the final security bugfix release for the **legacy 3.6 series which has now reached end-of-life** 

- Python 3.5.10: Release Date: Sept. 5, 2020
**Python 3.5 has reached end-of-life.** Python 3.5.10 is the final release of 3.5.
...
If you're still using Python 3.5, you should consider upgrading to the [current version.](https://www.python.org/downloads/) Newer versions of Python have many new features, performance improvements, and bug fixes, which should all serve to enhance your Python programming experience.

**Comment by connortann** [comment]
@kinverarity1 I don't think this issue is fully closed, as the documentation (e.g. the readme) still says python 3.5+

**Comment by dcslagel** [comment]
While the release documentation still says  python 3.5+, the  documentation on the main branch is 3.7+.   Also  the CI testing on the main branch is for `python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]`.

So I think making a release (including  pull-request #573) should bring the python version up-to-date.

Side-Note: I had hoped to finish the issue: "Flake8 maintenance for Lasio code " #564 before the next release but I've gotten busy for the time being.  So don't wait for "Flake8 maintenance for Lasio code " #564 to complete.  Go ahead with making the next release.

**Comment by connortann** [comment]
Shout out for [NEP 29 — Recommend Python and NumPy version support as a community policy standard](https://numpy.org/neps/nep-0029-deprecation_policy.html).

This standard supports having a predictable drop cycle that is common across scientific computing tools. Here is an extract from the recommended drop table:

```
On next release, drop support for Python 3.5 (initially released on Sep 13, 2015)
On Jun 23, 2020 drop support for Python 3.6 (initially released on Dec 23, 2016)
On Dec 26, 2021 drop support for Python 3.7 (initially released on Jun 27, 2018)
On Apr 14, 2023 drop support for Python 3.8 (initially released on Oct 14, 2019)
On Apr 05, 2024 drop support for Python 3.9 (initially released on Oct 05, 2020)
On Apr 04, 2025 drop support for Python 3.10 (initially released on Oct 04, 2021)
On Apr 24, 2026 drop support for Python 3.11 (initially released on Oct 24, 2022)
```
