### ISSUE TITLE
Add missing commands to to the installation doc.

### ISSUE THREAD

**Issue by dcslagel** [kinverarity1/lasio#551]
**Describe the bug**
Some install and update commands are missing from the Installation documentation in both the release version and the latest versions:

V0.30
https://lasio.readthedocs.io/en/v0.30/installation.html

Latest
https://lasio.readthedocs.io/en/latest/installation.html

**Expected behavior**
Display the following commands in their appropriate sections:
`pip install "lasio[all]"` 
`pip install --upgrade lasio` 
`$ pip install https://github.com/kinverarity1/lasio/archive/master.zip`

**Comment by dcslagel** [comment]
Note: The commands are visible when building the docs locally.  The differ

**Comment by dcslagel** [comment]
Notes:
- The unseen commands are formatted with code-block, but without a programming-language indicator:
```

.. code-block::

    $ pip install "lasio[all]"

```

Visible shell commands in installation.rst are formatted with code-block:: plus the `bash` language indicator:

```
.. code-block:: bash

    $ pip install lasio

```

**Comment by dcslagel** [comment]
Update: With the merge of Pull-Request #553 to main, this issue is fixed in the the latest docs.
https://lasio.readthedocs.io/en/latest/installation.html

**Comment by dcslagel** [comment]
@kinverarity1 ,  Continuing the discussion from issue # #561 about when to close issues.   What is your thinking on this one?

**Comment by kinverarity1** [comment]
Same as others 👍🏻
