### ISSUE TITLE
Reading las file with TAB DLM in ~version section result in KeyError: 'TAB'

### ISSUE THREAD

**Issue by tui95** [kinverarity1/lasio#554]
**Describe the bug**
When reading a las file that contains `TAB` as `DLM` in the `~version` section, a `KeyError: 'TAB'` occurs.

**To Reproduce**
With a modified of [standards/examples/3.0/sample_3.0.las](https://github.com/kinverarity1/lasio/blob/e6a1de69ed50f63ab5b3b967bc29344b62eabb17/standards/examples/3.0/sample_3.0.las) where the `~version` section is
```text
~VERSION INFORMATION
 VERS.                          3.0 : CWLS LOG ASCII STANDARD -VERSION 3.0
 WRAP.                           NO : ONE LINE PER DEPTH STEP
 DLM .                        TAB : DELIMITING CHARACTER BETWEEN DATA COLUMNS 
```
(notice the `DLM` line, where its value is `TAB`.)

I've got the following error

```shell
>>> las = lasio.read("sample_3.0.las")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/private/tmp/try-lasio/venv/lib/python3.9/site-packages/lasio/__init__.py", line 86, in read
    return LASFile(file_ref, **kwargs)
  File "/private/tmp/try-lasio/venv/lib/python3.9/site-packages/lasio/las.py", line 80, in __init__
    self.read(file_ref, **read_kwargs)
  File "/private/tmp/try-lasio/venv/lib/python3.9/site-packages/lasio/las.py", line 299, in read
    line_splitter = reader.define_line_splitter(provisional_delimiter)
  File "/private/tmp/try-lasio/venv/lib/python3.9/site-packages/lasio/reader.py", line 72, in define_line_splitter
    return splitters[provisional_delimiter]
KeyError: 'TAB'
```

**Expected behavior**
There should be no error, and the file can be read.

**Software versions:**
 - Python version: 3.9.0
 - Python distribution: pyenv
 - lasio version (`import lasio; print(lasio.__version__)`): 0.30

**Comment by dcslagel** [comment]
I verified that this same error will also be there in a LAS 2.0 file where the DLM == TAB and the data section is tab-delimited.  So its a general error not a LAS 3.0 specific error.

**Comment by dcslagel** [comment]
@tui95 , a fix for this has been merged to Lasio's main branch.  Could you give it a try to verify it resolves the problem you were seeing?

Thank you,
DC

**Comment by tui95** [comment]
@dcslagel I've verified that the fix solves the bug. Thank you.

**Comment by dcslagel** [comment]
@tui95 ,  Great!  Thank you for verifying.
