### ISSUE TITLE
Flake8 maintenance for test suite

### ISSUE THREAD

**Issue by dcslagel** [kinverarity1/lasio#561]
#### Description: 

This issue is to track overall work on updating the test suite to Flake8 conventions.

The work is being done on multiple pull-requests.

Pull-Requests:
- Flake8 maintenance: test_encodings.py #557
- Flake8 maintenance: tests/test_api.py #558
- Flake8 maintenance for test suite continued #559
- Flake8 maintenance for test suite continued #562
- Flake8 maintenance for test suite final set #563

**Comment by dcslagel** [comment]
@kinverarity1 , 

Should this issue be closed now that the work is complete or when the next release is made?

Thanks,
DC

**Comment by kinverarity1** [comment]
Good question! I think we should close issues when they are resolved in `main`, and (ideally) update the closed issue when the fix for it is released.
