### ISSUE TITLE
KeyError when reading LAS 2 file

### ISSUE THREAD

**Issue by KristianKjerstad** [kinverarity1/lasio#569]
**Describe the bug**
A KeyError occurs when reading LAS 2 file. 

The error happens in the following code in the SectionParser class ( in reader.py):

```python
        if self.section_name2 in defs[self.version]:
```

self.version is stored as the string '2.0' instead of the float 2.0, which causes a KeyError when accessing the `defs` dictionary.

**To Reproduce**
Try to load a las file like this:

```python
las = lasio.las.LASFile(file_ref=file_path)
```
[row3_example.las.zip](https://github.com/kinverarity1/lasio/files/11000086/row3_example.las.zip)

I have provided an example LAS 2 file that gives the error

**Software versions (please complete the following information):**
 - Python version: 3.10 and 3.8 tested. Both gave the error.

 - Python distribution: pip
 - lasio version 0.29

**Comment by kinverarity1** [comment]
Thanks for providing a report and example, I'll take a look!

**Comment by kinverarity1** [comment]
Sounds good! I don't know anything about poetry, so not sure what might be wrong. Feel free to re-open if you still have problems.
