### ISSUE TITLE
Request for new PyPI release, to support python 3.11

### ISSUE THREAD

**Issue by connortann** [kinverarity1/lasio#572]
The last release was over a year ago. Would it be possible to make a new release?

In my case, the aim is to enable support with python 3.11

**Comment by kinverarity1** [comment]
Thanks for the PR! 

Sure thing, I'm happy to make a new release when I have some time, hopefully sometime this week. 

Just a quick question, is there a bug or issue preventing lasio working on 3.11 at the moment?

**Comment by connortann** [comment]
As of the previous release (v 0.30) there was an import that is not available in python 3.11:

```
python3.11/site-packages/lasio/las_version.py:2: in <module>
    from pkg_resources import get_distribution, DistributionNotFound
E   ModuleNotFoundError: No module named 'pkg_resources'
```

However, that's now fixed in master, and I see you're running CI tests on python 3.11 too.

**Comment by connortann** [comment]
Thanks! Just in case you missed it, you may wish to review #573  before making the release, just to get the PyPI classifiers correct.

**Comment by kinverarity1** [comment]
done, thanks everyone
