### ISSUE TITLE
End Lasio support for Python 3.7 ?

### ISSUE THREAD

**Issue by dcslagel** [kinverarity1/lasio#574]
This issue opened to track when support for Python 3.7 is removed from Lasio.

Python.org states Python 3.7 with reach End-of-support on 2023-06-27
https://www.python.org/downloads/

Numpy's recommendations at 
https://numpy.org/neps/nep-0029-deprecation_policy.html 
This NEP recommends that all projects across the Scientific Python ecosystem adopt a common “time window-based” policy for support of Python and NumPy versions.
```
On Dec 26, 2021 drop support for Python 3.7 (initially released on Jun 27, 2018)
```

**Comment by kinverarity1** [comment]
Thanks for opening the issue

However, I'm not sure why we would drop support for 3.7 yet - Three and a half years is both a long time but also not. I definitely still have environments set up running 3.7, with no reason I'm aware of to spend time going in and upgrading them. I'd rather drop support when something is becoming a problem - are there any such problems with 3.7 yet?

**Comment by connortann** [comment]
Here's one argument for following the NEP (under "Alternatives: Ad Hoc version support"):

> A project could, on every release, evaluate whether to increase the minimum version of Python supported. As a major downside, an ad-hoc approach makes it hard for downstream users to predict what the future minimum versions will be. As there is no objective threshold to when the minimum version should be dropped, it is easy for these version support discussions to devolve into [bike shedding](https://en.wikipedia.org/wiki/Wikipedia:Avoid_Parkinson%27s_bicycle-shed_effect) and acrimony.

**Comment by kinverarity1** [comment]
Fair enough. I can guarantee lasio's pace of development is slow enough such that it will never be hard to predict a future minimum version. Clearly much more important is that we support the newest version... which I'll do now!

**Comment by connortann** [comment]
That makes sense. If there isn't much ongoing development and the prior versions still work, then I agree that supporting newer versions is a higher priority. I just like a good convention in the open source world that helps us align in a common direction :)

Regarding legacy projects - it's good to know that the previously-released versions of `lasio` are still available, so environments from legacy projects won't need any maintenance if they have their `lasio` version pinned.

**Comment by kinverarity1** [comment]
Certainly good to know - thank you for bringing it up and also posting the schedule!

Others, I'm happy to discuss further but will close the issue for now.
