### ISSUE TITLE
Need Help in understanding if there is a way to read commented out lines without raising header error.

### ISSUE THREAD

**Issue by Soumya3276** [kinverarity1/lasio#586]
So , I want to achieve something like:
In parameter section , if any attribute's value length is more than 64 character I want to comment out that line and write to the las file.
Problem I am facing is while reading it is not reading previously commented out attributes in parameter section so when I am writing to the las file it removes those previously commented attributes which I want to keep as it is in my las file only want to modify the new attribute as per logic.

So to do that I have used ignore_comments argument in read function but it raised header error. So I had to use ignore_header_errors. I want to know if there is a way to achieve that without raising header error. Any suggestions will be helpful on how to achieve that.

Python version = 3.18
Windows 10(64bit)
Lasio version = 0.31

**Picture of code is added**
![IMG_20240220_200953](https://github.com/kinverarity1/lasio/assets/71128338/07bf8ba4-9747-479b-a8f6-779502ddb153)

**Comment by Soumya3276** [comment]
### Ignoring commented-out lines

Sometimes data sections have comment line inside them. By default lasio will ignore any lines starting with the “#” character within the data section. You can control this using the _remove_data_line_filter='#'_ argument to [lasio.LASFile.read()](https://lasio.readthedocs.io/en/v0.29/lasio.html#lasio.LASFile.read).


I have found this in lasio documentation but is this still working? Because for me it is not. If it's still in use kindly help me with the syntax.

**Comment by kinverarity1** [comment]
@Soumya3276 in response to your comment immediately above regarding remove_data_line_filter='#' - this would only apply within data sections. From what I gather your comment relates to comment lines in the well/parameter/curves sections.

> So , I want to achieve something like:
> In parameter section , if any attribute's value length is more than 64 character I want to comment out that line and write to the las file.
> Problem I am facing is while reading it is not reading previously commented out attributes in parameter section so when I am writing to the las file it removes those previously commented attributes which I want to keep as it is in my las file only want to modify the new attribute as per logic.

This sounds like quite a low-level manipulation of LAS file format which would not be something lasio performs. Although I agree #14 is a desirable feature, it has not been implemented, and I have no time to work on lasio development myself at the moment. I would be happy to review a PR though.
