### ISSUE TITLE
Reader error

### ISSUE THREAD

**Issue by Soumya3276** [kinverarity1/lasio#591]
I am new to lasio so maybe I am missing some existing parameter. All I want to do is read a LAS file , make some changes in well, curve , parameter and other section and write them back to LAS files.

But the issue that frustrates me is that there should be a way to read commented out lines(#) in header section as well. By default it is removing all the commented out lines while writing.

**If anything exist already please suggest.**

**To Reproduce**
Just open a LAS file
Make some changes in WELL SECTION like API, UWI, STAT or any parameter , Curve mnemonics/units in Curve section and write them back to las file.

**Expected behavior**
All I want lasio is to read the commented out lines in those sections and write them back as it is without altering. Currently It is removing commented out lines.

**Software versions (please complete the following information):**
 - Python version: 3.18 ( Windows 10, 64 bit)
 - Python distribution : Miniconda
 - lasio version (`import lasio; print(lasio.__version__)`) 0.31

**Additional context**
Cannot share las file due to confidentiality.

**Comment by kinverarity1** [comment]
Closing as duplicate #14
