### ISSUE TITLE
Badge open issue don't match open issues of GitHub

### ISSUE THREAD

**Issue by VelizarVESSELINOV** [kinverarity1/lasio#65]
Badge: 28, GitHub: 25
<img width="538" alt="screen shot 2015-08-09 at 9 59 49 am" src="https://cloud.githubusercontent.com/assets/8209940/9155923/8f9eed8c-3e7d-11e5-8ddd-6be2895faac6.png">

**Comment by kinverarity1** [comment]
Good point... not working for me now for some reason.
