### ISSUE TITLE
forced number formatting

### ISSUE THREAD

**Issue by bsdis** [kinverarity1/lasio#66]
I am writing large values such as 1393323269.0 into my lasfile.
https://github.com/kinverarity1/lasio/blob/master/lasio/las.py#L372 forces encoding of these values such that they in the LAS file are shown as 1.393e+09 which throws critical information away.
Could it be made such that formatting is optional?

**Comment by kinverarity1** [comment]
I have added the keyword argument ``fmt="%10.5g"`` to the ``LASFile.write`` method. So you should be able use any [string formatting specification](https://docs.python.org/2/library/stdtypes.html#string-formatting):

```python
>>> n = 1393323269.0
>>> "%10.5g" % n
'1.3933e+09'
>>> "%20f" % n
'   1393323269.000000'
```

**Comment by kinverarity1** [comment]
@diverdude, let me know if this is fixed in master now.

Cheers
