### ISSUE TITLE
Create Docker image with lasio (enhancement)

### ISSUE THREAD

**Issue by VelizarVESSELINOV** [kinverarity1/lasio#71]
Personally I'm using a lot [Python Docker image](https://hub.docker.com/_/python/) and often I need to include lasio, cchardet, it will be nice to have certified lasio image and there are extra docker badges to win :+1:

**Comment by kinverarity1** [comment]
http://betatim.github.io/posts/project-everware-reusable-science/

**Comment by VelizarVESSELINOV** [comment]
It is very good to see Jupyter and Docker association, if you are looking for basic example of Docker with lasio you can find this: https://github.com/VelizarVESSELINOV/DockerTest or take it execute it from  https://hub.docker.com/r/velizar/test1/
I created this project to demonstrate a "bug" in Docker.

**Comment by kinverarity1** [comment]
Thanks for the examples -- I'm still learning about Docker but would certainly like to assist where possible.

**Comment by kinverarity1** [comment]
OK I'm still a bit new to Docker but see https://hub.docker.com/r/kinverarity/lasio/

The Docker container is pretty simple, just installs lasio and its dependencies and optional packages. And that DockerHub repo will build automatically from the latest version of lasio here on Github.

That's the idea, right?
