### ISSUE TITLE
<class 'KeyError'> error: 'NULL'"

### ISSUE THREAD

**Issue by VelizarVESSELINOV** [kinverarity1/lasio#76]
I found files that don't have NULL defined, I know that this is against the LAS standard but if you can soften the  check it will be helpful. I think with previous version of lasio/las_reader was possible to read these files.
The files don't contains NULL values in ~A section. If you replace the exception with warning it will be perfect for non fully standard LAS files management.

**Comment by kinverarity1** [comment]
Agreed, I've run into this too already and it will work well with #49's auto null detection.

**Comment by kinverarity1** [comment]
Fixed now, ``logging.warning`` is used instead.
