### ISSUE TITLE
<class 'lasio.las.LASHeaderError'> error: Failed in ~W section on line:

### ISSUE THREAD

**Issue by VelizarVESSELINOV** [kinverarity1/lasio#80]
Sorry to add so many tickets but I just finished to parse more than 50000 LAS files from different sources and listing the common error reading patterns I was able to identify.

I would suggest to turn it as warning, similar request to #53 

```
<class 'lasio.las.LASHeaderError'> error: Failed in ~W section on line:\n\"# Surface Coords: 1,000' FNL & 2,000' FWL\"AttributeError: 'NoneType' object has no attribute 'groupdict'",
```

```
API       .                                          : API Number     (required if CTRY = US)   
"# Surface Coords: 1,000' FNL & 2,000' FWL" 
LATI      .DEG                                       : Latitude  - see Surface Coords comment above 
LONG      .DEG                                       : Longitude - see Surface Coords comment above 
```

**Comment by kinverarity1** [comment]
No, tickets are excellent, they make it vastly easier for me to work on the project when I am pressed for time. Thanks!

**Comment by kinverarity1** [comment]
With PR #170, the requested behaviour can be had with ``ignore_header_errors=True`` (then a warning will be issued instead).
