### ISSUE TITLE
Easier interpretation of LASDataError line error

### ISSUE THREAD

**Issue by VelizarVESSELINOV** [kinverarity1/lasio#86]
```
lasio.las.LASDataError: Failed to read data:
ValueError: Wrong number of columns at line 16098
```

If my understanding is correct 16098 is relative line number from ~A.

Suggestion for improvement:
- display the real line number 16098 + 79 (in my case)
- display the content of the line, instead searching in the file that line

(Sorry to bug with you with this but when I have 2000 files with errors to analyze it is painful to do these extra tasks to debug if the LAS file is completely wrong or the library missed some special cases)

**Comment by kinverarity1** [comment]
as of #170 lasio shows both the failing line and the true line number.
