### ISSUE TITLE
Please add correct BOM management

### ISSUE THREAD

**Issue by VelizarVESSELINOV** [kinverarity1/lasio#93]
If the file is saved with BOM is not correctly parsed: 
<img width="178" alt="screen shot 2015-08-12 at 4 18 02 pm" src="https://cloud.githubusercontent.com/assets/8209940/9239143/d202ecc2-410d-11e5-8d9d-ecdd0d5e3c06.png">

Code:
```
from lasio import read
f = 'tata.las'
l = read(f, autodetect_encoding=True)
```

Exception:
```
    raise KeyError("No key VERS in ~V section")
KeyError: 'No key VERS in ~V section'
```

Example of normal file header:
```
~Version Information
 #MNEM.UNIT                                                       DATA   DESCRIPTION
 #---------                                                       ----   -----------
 VERS.                                                             2.0 : CWLS LOG ASCII STANDARD - VERSION 2.0
 WRAP.                                                              NO : ONE LINE PER DEPTH STEP
 DLM.                                                            SPACE : COLUMN DATA SECTION DELIMITER
~Well Information
```

**Comment by kinverarity1** [comment]
I've had a look at this and am finding that ``chardet`` is not great at distinguishing between UTF8 with and without a BOM.

You can load them correctly by specifying the encoding as either ``utf-8`` or ``utf-8-sig``, but beyond that I'm not aware of how to distinguish them automatically.

I'm about to push some changes improving logger.debug messages sent out regarding encodings - the package was a bit messy and not keeping strings as unicode objects internally. I'm also trying to start work on a test suite for encoding detection.

**Comment by VelizarVESSELINOV** [comment]
Please find a link with examples of code detecting BOM: http://stackoverflow.com/questions/13590749/reading-unicode-file-data-with-bom-chars-in-python

**Comment by kinverarity1** [comment]
Thanks, yeah I did look into it some more thus the deleted comment! - see PR #96 which will be merged once a few bits are ironed out.

Still won't be perfect but the shortcomings are/will be due to [c]chardet rather than lasio.

**Comment by kinverarity1** [comment]
UTF-8 BOM detection is worked and there are now automated tests for it too, so closing.
