### ISSUE TITLE
Create pandas.DataFrame attribute storing log data

### ISSUE THREAD

**Issue by kinverarity1** [kinverarity1/lasio#94]
This used to be in there but it made more sense to require only numpy.

However, if the user has pandas available then we should use it. Call the attribute ``df`` and use the reference curve as the index for the DataFrame.

**Comment by kwinkunks** [comment]
Just wanted to +1 this. It would make a great optional dependency. 

I don't know that these will help, but to illustrate a use case, the notebooks [here](https://github.com/seg/tutorials/tree/master/1504_Seismic_petrophysics_1) and [here](https://github.com/seg/tutorials/tree/master/1506_Seismic_petrophysics_2) use pandas for some rock physics calculations.

**Comment by kinverarity1** [comment]
Still to-do before this issue is closed:

- Add example to the documentation
- The only unit test at the moment tests that the reference curve from the LAS file is correctly used as the index in the DataFrame and Series, but I need to add tests for the presence of the curves and also a reverse-direction LAS file index -- although it will probably work it's not being tested.

**Comment by kinverarity1** [comment]
Curve names also checked now - 0082159
